vhdl-sources += pmod_ethernet.pkg.vhd
vhdl-sources += pmod_ethernet_mdi.vhd
vhdl-sources += pmod_ethernet_10baset_mau.vhd
vhdl-sources += pmod_ethernet_axi4_stream.vhd

deps += nsl_digilent.pmod
deps += nsl_io.pad
deps += nsl_io.diff
deps += nsl_8023.mau_10baset
deps += nsl_mii.flit
deps += nsl_amba.axi4_stream
