vhdl-sources += clock.pkg.vhd
vhdl-sources += clock_adjustable.vhd
vhdl-sources += clock_from_pps.vhd
deps += nsl_math.fixed
deps += nsl_event.tick
deps += nsl_dsp.box
deps += nsl_time.timestamp
deps += nsl_math.arith
