vhdl-sources += vlan.pkg.vhd
vhdl-sources += vlan_demux.vhd
vhdl-sources += vlan_mux.vhd
vhdl-sources += vlan_path_router.vhd

deps += nsl_logic.bool
deps += nsl_data.bytestream
deps += nsl_data.endian
deps += nsl_bnoc.committed
deps += nsl_math.arith
deps += nsl_inet.mac
deps += nsl_amba.axi4_stream
deps += nsl_bnoc.axi_adapter
