vhdl-sources += func.pkg.vhd 
vhdl-sources += serial_port.vhd  

deps += nsl_clocking.async
deps += nsl_logic.bool
deps += nsl_math.arith
deps += nsl_usb.descriptor
deps += nsl_usb.device
deps += nsl_usb.sie
deps += nsl_usb.usb
deps += nsl_usb.utmi
