target = blink
top = work.top
work-srcdir = $(SRC_DIR)/../src
target_part = GW1N-LV1
target_package = QN48
target_speed = C6/I5
hwdep = gowin
tool = gowin

all: blink.fs

include ../../../build/build.mk
