#!/usr/bin/env python2

import sys

mode = sys.argv[1]
src = int(sys.argv[2])
for peer in map(int, sys.argv[3:]):
    if mode == "src":
        print 256 + src * 16 + peer, 0
    else:
        print 256 + peer * 16 + src, 0
    for i in range(39):
        print 256 + i, 0
    print 40, 0
