#!/usr/bin/env python2

import sys

mode = sys.argv[1]
src = int(sys.argv[2])
for size in range(2, 32):
    for peer in map(int, sys.argv[3:]):
        print size, 0
        if mode == "src":
            print src * 16 + peer, 0
        else:
            print peer * 16 + src, 0
        for i in range(size - 1):
            print 0x80 + i, 0
