vhdl-sources += cbor_transactor.pkg.vhd
vhdl-sources += axi4stream_cbor_sdio_transactor.vhd

deps += nsl_sdio.sdio
deps += nsl_sdio.host
deps += nsl_amba.axi4_stream
deps += nsl_data.cbor
deps += nsl_data.bytestream
deps += nsl_logic.bool
deps += nsl_sdio.link
