vhdl-sources += testing.pkg.vhd

deps += nsl_mii.mii
deps += nsl_mii.rgmii
deps += nsl_data.bytestream
deps += nsl_data.crc
deps += nsl_data.endian
deps += nsl_data.text
deps += nsl_simulation.logging
deps += nsl_logic.bool
