vhdl-sources += terminal_text_buffer.vhd
vhdl-sources += terminal.pkg.vhd

deps += nsl_memory.ram
deps += nsl_memory.streamer
deps += nsl_data.bytestream
deps += nsl_data.endian
deps += nsl_logic.logic
deps += nsl_logic.bool
deps += nsl_color.rgb
deps += nsl_math.arith
deps += nsl_indication.font
