vhdl-sources += testing.pkg.vhd

deps += nsl_usb.usb
deps += nsl_usb.utmi
deps += nsl_usb.debug
deps += nsl_data.text
deps += nsl_simulation.logging
deps += nsl_data.crc
deps += nsl_data.endian
deps += nsl_data.bytestream
