vhdl-sources += stream_fifo.pkg.vhd
vhdl-sources += axi4_stream_fifo.vhd
vhdl-sources += axi4_stream_fifo_cancellable.vhd
vhdl-sources += axi4_stream_slice.vhd
vhdl-sources += axi4_stream_cdc.vhd


deps += nsl_memory.fifo
deps += nsl_amba.axi4_stream
deps += nsl_clocking.interdomain
