vhdl-sources += stream_fifo.pkg.vhd
vhdl-sources += axi4_stream_fifo.vhd
vhdl-sources += axi4_stream_fifo_cancellable.vhd
vhdl-sources += axi4_stream_slice.vhd
vhdl-sources += axi4_stream_cdc.vhd
vhdl-sources += axi4_stream_fifo_atomic.vhd
vhdl-sources += axi4_stream_fifo_clean.vhd
vhdl-sources += axi4_stream_async_packet_drop_fifo.vhd

deps += nsl_memory.fifo
deps += nsl_memory.streamer
deps += nsl_amba.axi4_stream
deps += nsl_clocking.interdomain
