vhdl-sources += arp.pkg.vhd
vhdl-sources += arp_ethernet.vhd
vhdl-sources += arp_resolver.vhd

deps += nsl_math.arith
deps += nsl_bnoc.committed
deps += nsl_bnoc.framed
deps += nsl_memory.ram
deps += nsl_data.bytestream
deps += nsl_data.endian
deps += nsl_inet.ethernet

