vhdl-sources += packetizer.pkg.vhd
vhdl-sources += committed_packetizer.vhd
vhdl-sources += committed_unpacketizer.vhd
vhdl-sources += committed_unpacketizer_filter.vhd

deps += nsl_data.bytestream
deps += nsl_bnoc.committed
deps += nsl_bnoc.framed
