vhdl-sources += boundary.vhd
deps += nsl_hwdep.clock
deps += nsl_hwdep.reset
deps += nsl_sipeed.pmod_dtx2
deps += nsl_clocking.async
deps += nsl_clocking.distribution

deps += nsl_data.bytestream

sdc-sources += ../../pinout/clk.sdc
constraint-sources += ../../pinout/buttons.cst
constraint-sources += ../../pinout/clk.cst
constraint-sources += ../../pinout/j4_pmod_double_lvcmos33.cst
