vhdl-sources += tb.vhd
deps += nsl_bnoc.framed
deps += nsl_bnoc.routed
deps += nsl_bnoc.testing
deps += nsl_i2c.i2c
deps += nsl_i2c.transactor
deps += nsl_i2c.clocked
deps += nsl_clocking.async
deps += nsl_simulation.driver

