vhdl-sources += xadc.pkg.vhd
vhdl-sources += xadc_wrapper.vhd
vhdl-sources += xadc_continuous.vhd

deps += nsl_data.text
deps += nsl_math.fixed
deps += nsl_io.diff
deps += nsl_logic.bool
deps += unisim.vcomponents
