vhdl-sources += testbench.vhd

deps += nsl_clocking.async
deps += nsl_coresight.swd
deps += nsl_coresight.transactor
deps += nsl_bnoc.routed
deps += nsl_simulation.driver
deps += nsl_bnoc.testing
deps += design.fpga_io
