vhdl-sources += root.pkg.vhd
vhdl-sources += tb.vhd
vhdl-sources += dut.vhd

deps += nsl_inet.ethernet
deps += nsl_mii.link_monitor
deps += nsl_mii.rgmii
deps += nsl_mii.testing
deps += nsl_data.text
deps += nsl_data.bytestream
deps += nsl_bnoc.testing
deps += nsl_simulation.driver
deps += nsl_simulation.assertions
