vhdl-sources += timestamping.pkg.vhd
vhdl-sources += timestamping_rx_tagger.vhd
vhdl-sources += timestamping_tx_strober.vhd
vhdl-sources += timestamping_sideband_resync.vhd

deps += nsl_amba.axi4_stream
deps += nsl_data.bytestream
deps += nsl_logic.bool
deps += nsl_math.int_ext
deps += nsl_clocking.interdomain
