vhdl-sources += chunked_link.pkg.vhd
vhdl-sources += chunked_link_chunker.vhd
vhdl-sources += chunked_link_slave_framer.vhd
vhdl-sources += chunked_link_master_framer.vhd
vhdl-sources += chunked_link_deframer.vhd
vhdl-sources += framed_chunker.vhd
vhdl-sources += framed_unchunker.vhd

deps += nsl_data.bytestream
deps += nsl_bnoc.framed
deps += nsl_bnoc.pipe
deps += nsl_memory.fifo
