vhdl-sources += chunked_link.pkg.vhd
vhdl-sources += chunked_link_chunker.vhd
vhdl-sources += chunked_link_slave_framer.vhd
vhdl-sources += chunked_link_master_framer.vhd
vhdl-sources += chunked_link_deframer.vhd

deps += nsl_data.bytestream
