vhdl-sources += stream.pkg.vhd
vhdl-sources += i2s_stream_transmitter.vhd
vhdl-sources += i2s_stream_receiver.vhd

deps += nsl_amba.axi4_stream
deps += nsl_audio.pcm
deps += nsl_audio.pcm_stream
deps += nsl_synthesis.assertion
