vhdl-sources += pct2075.pkg.vhd
vhdl-sources += pct2075_reader.vhd

deps += nsl_bnoc.framed
deps += nsl_bnoc.framed_transactor
deps += nsl_data.bytestream
deps += nsl_data.endian
deps += nsl_logic.bool
deps += nsl_i2c.transactor
