vhdl-sources += clockfree.pkg.vhd
vhdl-sources += clockfree_slave.vhd
vhdl-sources += clockfree_memory_controller.vhd
vhdl-sources += clockfree_memory.vhd
vhdl-sources += clockfree_control_bank.vhd
deps += nsl_math.arith
deps += nsl_i2c.i2c
