vhdl-sources += boundary.vhd
implementation_constraint-sources += pins.xdc
synthesis_constraint-sources += clocks.xdc

deps += nsl_i2c.i2c
deps += entry.neorv32_tester
deps += nsl_hwdep.clock
deps += nsl_hwdep.uid
deps += nsl_hwdep.reset
deps += nsl_clocking.async
deps += nsl_ws.driver
deps += nsl_indication.activity
deps += nsl_color.rgb
deps += nsl_io.clock
deps += nsl_io.io
deps += nsl_spi.io_extender
