set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 2 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 66 [current_design]

set_property CFGBVS GND [current_design]
set_property CONFIG_VOLTAGE 1.8 [current_design]
#set_property INTERNAL_VREF 0.9 [get_iobanks 33]
#set_property INTERNAL_VREF 0.9 [get_iobanks 34]

# Bank 14, fixed 1.8V
set_property PACKAGE_PIN N14 [get_ports clock_60_i]
set_property IOSTANDARD LVCMOS18 [get_ports {clock_60_i}]

set_property PACKAGE_PIN P14 [get_ports {phy_data_io[0]}]
set_property PACKAGE_PIN P15 [get_ports {phy_data_io[1]}]
set_property PACKAGE_PIN P16 [get_ports {phy_data_io[2]}]
set_property PACKAGE_PIN N12 [get_ports {phy_data_io[3]}]
set_property PACKAGE_PIN N13 [get_ports {phy_data_io[4]}]
set_property PACKAGE_PIN M16 [get_ports {phy_data_io[5]}]
set_property PACKAGE_PIN N16 [get_ports {phy_data_io[6]}]
set_property PACKAGE_PIN R15 [get_ports {phy_data_io[7]}]
set_property PACKAGE_PIN P13 [get_ports {phy_nxt_i}]
set_property PACKAGE_PIN T12 [get_ports {phy_clk_o}]
set_property PACKAGE_PIN R16 [get_ports {phy_dir_i}]
set_property PACKAGE_PIN R13 [get_ports {phy_stp_o}]
set_property PACKAGE_PIN T13 [get_ports {phy_reset_n_o}]
set_property IOSTANDARD LVCMOS18 [get_ports {phy_*}]

set_property PACKAGE_PIN R11 [get_ports {i2c_sda_io}]
set_property PACKAGE_PIN T10 [get_ports {i2c_scl_io}]
set_property IOSTANDARD LVCMOS18 [get_ports {i2c_*}]

set_property PACKAGE_PIN K12 [get_ports {flash_sel_d_o}]
set_property PACKAGE_PIN K13 [get_ports {flash_sel_c_o}]
set_property PACKAGE_PIN G15 [get_ports {flash_sel_o}]
set_property PACKAGE_PIN J13 [get_ports {flash_d_io[0]}]
set_property PACKAGE_PIN J14 [get_ports {flash_d_io[1]}]
set_property PACKAGE_PIN L12 [get_ports {flash_cs_n_o}]
set_property -dict {IOSTANDARD LVCMOS18 SLEW SLOW DRIVE 4} [get_ports {flash_*}]

# Bank 35, on FPGA board. Should work with any reference voltage.
set_property PACKAGE_PIN L3 [get_ports {led_ctrl_o}]
set_property IOSTANDARD LVCMOS18 [get_ports {led_ctrl_o}]

set_property PACKAGE_PIN K3 [get_ports {button_n_i[1]}]
set_property PACKAGE_PIN K2 [get_ports {button_n_i[2]}]
set_property PACKAGE_PIN J5 [get_ports {button_n_i[3]}]
set_property PACKAGE_PIN J4 [get_ports {button_n_i[4]}]
set_property -dict {IOSTANDARD LVCMOS18 PULLUP true} [get_ports {button_n_i*}]

# # Bank 15/35, on mezzanine connectors, dbg_cortex0 specific.
# set_property PACKAGE_PIN C7 [get_ports {xadc_vsense_p}]
# set_property PACKAGE_PIN C6 [get_ports {xadc_vsense_n}]
# set_property PACKAGE_PIN C8 [get_ports {xadc_isense_p}]
# set_property PACKAGE_PIN C9 [get_ports {xadc_isense_n}]
# 
# set_property PACKAGE_PIN C11 [get_ports {tgtmgmt_supply_over_n_i}]
# set_property PACKAGE_PIN C12 [get_ports {tgtmgmt_supply_en_o}]
# set_property PACKAGE_PIN B9  [get_ports {tgtmgmt_reset_drain}]
# set_property PACKAGE_PIN A9  [get_ports {tgtmgmt_detect_drain}]
# set_property PACKAGE_PIN E12 [get_ports {tgtmgmt_vref_o[0]}]
# set_property PACKAGE_PIN D14 [get_ports {tgtmgmt_vref_o[1]}]
# set_property PACKAGE_PIN D15 [get_ports {tgtmgmt_vref_o[2]}]
# set_property PACKAGE_PIN E13 [get_ports {tgtmgmt_vref_o[3]}]
# set_property -dict {IOSTANDARD LVCMOS18 SLEW SLOW DRIVE 4} [get_ports {tgtmgmt_*}]
# 
# # Bank 34, Using Target VREF, 0.8-3.3V
# set_property PACKAGE_PIN P5 [get_ports {target_ext_io[0]}]
# set_property PACKAGE_PIN M5 [get_ports {target_ext_io[1]}]
# set_property PACKAGE_PIN N4 [get_ports {target_ext_io[2]}]
# set_property PACKAGE_PIN P3 [get_ports {target_ext_io[3]}]
# set_property PACKAGE_PIN R3 [get_ports {target_ext_io[4]}]
# set_property PACKAGE_PIN N3 [get_ports {target_ext_io[5]}]
# set_property PACKAGE_PIN M4 [get_ports {target_tdi_io}]
# set_property PACKAGE_PIN L5 [get_ports {target_tdo_io}]
# set_property PACKAGE_PIN M1 [get_ports {target_tms_io}]
# set_property PACKAGE_PIN L4 [get_ports {target_tck_io}]
# set_property PACKAGE_PIN N2 [get_ports {target_reset_n_i}]
# set_property PULLUP true [get_ports {target_tms_io target_tdi_io}]
# set_property PULLDOWN true [get_ports {target_tck_io target_tdo_io}]
# set_property -dict {IOSTANDARD LVCMOS33 SLEW SLOW DRIVE 4} [get_ports {target_*}]
