vhdl-sources += fifo.vhd

#vhdl-sources += fifo_2p.vhd
vhdl-sources += fifo_write_pointer.vhd
vhdl-sources += fifo_read_pointer.vhd
vhdl-sources += fifo_2p_ram2.vhd

deps += util.sync
deps += util.numeric
deps += util.gray
deps += hwdep.ram
