vhdl-sources += tb.vhd
deps += nsl_simulation.driver
deps += nsl_bnoc.framed
deps += nsl_bnoc.testing
deps += nsl_inet.ethernet
deps += nsl_inet.ipv4
deps += nsl_inet.udp
deps += nsl_inet.tcp
deps += nsl_inet.testing
deps += nsl_clocking.async

