vhdl-sources += clocked.pkg.vhd
vhdl-sources += clocked_memory.vhd
vhdl-sources += clocked_memory_controller.vhd
vhdl-sources += clocked_slave.vhd
deps += nsl_clocking.async
deps += nsl_math.arith
deps += hwdep.ram
