vhdl-sources += clocked.pkg.vhd
vhdl-sources += clocked_memory.vhd
vhdl-sources += clocked_memory_controller.vhd
vhdl-sources += clocked_slave.vhd
deps += nsl_i2c.i2c
deps += nsl_clocking.async
deps += nsl_math.arith
deps += nsl_memory.ram
