vhdl-sources += receiver.pkg.vhd
vhdl-sources += i2s_receiver.vhd
vhdl-sources += i2s_receiver_master.vhd
vhdl-sources += i2s_receiver_slave.vhd

deps += nsl_clocking.async
deps += nsl_i2s.clock
deps += nsl_math.arith

