vhdl-sources += st7735.pkg.vhd
vhdl-sources += st7735_spi_driver.vhd

deps += nsl_spi.spi
deps += nsl_data.bytestream
deps += nsl_color.rgb
deps += nsl_video.pixel_stream
deps += nsl_video.raster
deps += nsl_video.mode
