vhdl-sources += boundary.vhd
deps += nsl_hwdep.clock
deps += nsl_hwdep.reset
deps += nsl_sipeed.pmod_dtx2
deps += nsl_sipeed.pmod_8xled
deps += nsl_clocking.async
deps += nsl_clocking.distribution

deps += nsl_data.bytestream

constraint-sources += ../../pinout/buttons.xdc
constraint-sources += ../../pinout/clk100.xdc
constraint-sources += ../../pinout/ja_lvcmos33.xdc
constraint-sources += ../../pinout/jb_lvcmos33.xdc
