vhdl-sources += transceiver.pkg.vhd
vhdl-sources += spdif_rx_recovery.vhd
vhdl-sources += spdif_tx.vhd
deps += nsl_spdif.serdes
deps += nsl_spdif.framer
deps += nsl_spdif.blocker
deps += nsl_data.bytestream
deps += nsl_data.endian
