vhdl-sources += framed.pkg.vhd
vhdl-sources += framed_fifo.vhd
vhdl-sources += framed_fifo_atomic.vhd
vhdl-sources += framed_arbitrer.vhd
vhdl-sources += framed_committer.vhd

deps += nsl_memory.fifo
deps += nsl_math.arith
