vhdl-sources += framed.pkg.vhd
vhdl-sources += framed_fifo.vhd
vhdl-sources += framed_fifo_atomic.vhd
vhdl-sources += framed_arbitrer.vhd
vhdl-sources += framed_fifo_slice.vhd
vhdl-sources += framed_gate.vhd
vhdl-sources += framed_granted_gate.vhd
vhdl-sources += framed_gate_arbitrer.vhd
vhdl-sources += framed_funnel.vhd
vhdl-sources += framed_dispatch.vhd
vhdl-sources += framed_committer.vhd
vhdl-sources += framed_framer.vhd
vhdl-sources += framed_unframer.vhd

deps += nsl_memory.fifo
deps += nsl_bnoc.pipe
deps += nsl_math.arith
deps += nsl_logic.bool
