vhdl-sources += ibm_8b10b_stream.pkg.vhd
vhdl-sources += ibm_8b10b_stream_idle_filter.vhd

deps += nsl_line_coding.ibm_8b10b
deps += nsl_amba.axi4_stream
deps += nsl_amba.stream_fifo
deps += nsl_data.bytestream
