target = color_priority_encoder
top = work.top
work-srcdir = $(SRC_DIR)/../src
target_part = xc6slx9
target_package = tqg144
target_speed = -2
hwdep = xilinx
tool = ise

all: color_priority_encoder-compressed.bit

include ../../../build/build.mk
