vhdl-sources += frontend.pkg.vhd
vhdl-sources += axi4_mm_burst_adapter.vhd
deps += nsl_amba.axi4_mm
deps += nsl_ext_ram.burst
deps += nsl_data.bytestream
deps += nsl_math.arith
deps += nsl_logic.bool
