vhdl-sources += stream_mac.pkg.vhd
vhdl-sources += stream_mac_receiver.vhd
vhdl-sources += stream_mac_transmitter.vhd

deps += nsl_amba.axi4_stream
deps += nsl_data.bytestream
deps += nsl_data.crc
deps += nsl_inet.mac
deps += nsl_inet.stream
deps += nsl_logic.bool
deps += nsl_math.int_ext
