vhdl-sources += fifo.pkg.vhd
vhdl-sources += fifo_sync.vhd
vhdl-sources += fifo_async.vhd
vhdl-sources += fifo_narrower.vhd
vhdl-sources += fifo_delayed_writer.vhd
vhdl-sources += fifo_input_stabilized.vhd

deps += hwdep.fifo
