vhdl-sources += fifo.vhd
vhdl-sources += fifo_sync.vhd
vhdl-sources += fifo_async.vhd
vhdl-sources += fifo_narrower.vhd
vhdl-sources += fifo_framed.vhd
vhdl-sources += fifo_framed_async.vhd
vhdl-sources += fifo_framed_atomic.vhd
