vhdl-sources += fifo.vhd
vhdl-sources += fifo_sync.vhd
vhdl-sources += fifo_async.vhd
vhdl-sources += fifo_narrower.vhd
vhdl-sources += fifo_framed.vhd
vhdl-sources += fifo_framed_async.vhd
vhdl-sources += fifo_framed_atomic.vhd
vhdl-sources += fifo_framed_router.vhd
vhdl-sources += fifo_framed_router_inbound.vhd
vhdl-sources += fifo_framed_router_outbound.vhd
vhdl-sources += fifo_framed_endpoint.vhd

deps += nsl.fifo
deps += nsl.util
deps += hwdep.fifo
