vhdl-sources += axi4_stream.pkg.vhd
vhdl-sources += axi4_stream_fifo.vhd
vhdl-sources += axi4_stream_dumper.vhd

deps += nsl_math.arith
deps += nsl_logic.bool
deps += nsl_data.bytestream
deps += nsl_data.endian
deps += nsl_data.text
deps += nsl_memory.fifo
deps += nsl_simulation.logging
