vhdl-sources += fast_serial.pkg.vhd
vhdl-sources += fast_serial_tx.vhd
vhdl-sources += fast_serial_rx.vhd
vhdl-sources += fast_serial_master.vhd
vhdl-sources += fast_serial_slave.vhd
deps += nsl_clocking.async
