top = work.ip_top

ip-taxonomy = /AXI
ip-library = memory
ip-name = axi4lite_bram
ip-version = 1.0
ip-revision = 1
ip-display-name = AXI4-Lite BRAM
ip-description = Block ram

include ../packaging.mk
