top = work.ip_top

ip-taxonomy = /AXI
ip-library = memory
ip-name = axi4lite_drp_driver
ip-version = 1.1
ip-revision = 2
ip-display-name = AXI4-Lite DRP drivr
ip-description = DRP

include ../packaging.mk
