vhdl-sources += i2c.vhd
vhdl-sources += i2c_master.vhd
vhdl-sources += i2c_framed_ctrl.vhd
vhdl-sources += i2c_slave.vhd
vhdl-sources += i2c_mem.vhd
deps += nsl.framed
deps += util.sync
deps += signalling.i2c
