vhdl-sources += i2c.pkg.vhd
vhdl-sources += i2c_master.vhd
vhdl-sources += i2c_mem_ctrl.vhd
vhdl-sources += i2c_mem_ctrl_clocked.vhd
vhdl-sources += i2c_framed_ctrl.vhd
vhdl-sources += i2c_slave.vhd
vhdl-sources += i2c_slave_clkfree.vhd
vhdl-sources += i2c_slave_clocked.vhd
vhdl-sources += i2c_mem.vhd
vhdl-sources += i2c_mem_clocked.vhd
vhdl-sources += i2c_control_bank.vhd

deps += nsl.framed
deps += nsl.routed
deps += util.sync
deps += util.numeric
deps += signalling.i2c
