vhdl-sources += dut.vhd
vhdl-sources += tb.vhd

deps += nsl_hwdep.reset
deps += nsl_clocking.async
deps += nsl_memory.fifo
deps += nsl_usb.testing
deps += nsl_usb.utmi
deps += nsl_usb.func
deps += nsl_usb.usb
deps += nsl_data.text
deps += nsl_data.bytestream
deps += nsl_data.prbs
deps += nsl_data.crc
deps += nsl_simulation.control
deps += nsl_simulation.logging
