vhdl-sources += usb_commands.vhd
vhdl-sources += dut.vhd
vhdl-sources += tb.vhd

deps += nsl_hwdep.reset
deps += nsl_clocking.async
deps += nsl_memory.fifo
deps += nsl_usb.usb
deps += nsl_usb.utmi
deps += nsl_usb.debug
deps += nsl_usb.func
deps += nsl_simulation.text
deps += nsl_simulation.control
deps += nsl_simulation.logging
deps += nsl_data.endian
deps += nsl_data.bytestream
deps += nsl_data.prbs
