"""
Pytest configuration for VHDL testbenches.

This module provides infrastructure to:
1. Discover VHDL testbenches in subdirectories
2. Run simulations and save their stdout/stderr to log files
3. Parse report.txt generated by each testbench for test results
4. Report individual test results from each testbench
"""

import subprocess
import re
from pathlib import Path
from dataclasses import dataclass
from typing import Optional

import pytest

# Paths are relative to the tests root (where conftest.py lives)
VHDL_TESTBENCHES_TO_RUN = [
    "i2c_cbor/full_test",
    "spi_cbor/full_test",
    "jtag_cbor/full_test",
    "swd_cbor/full_test",
    "uart_cbor/full_test"
]

@dataclass
class VhdlTestResult:
    """Result of a single test within a VHDL testbench."""
    number: int
    name: str
    passed: bool


@dataclass
class VhdlSimulationResult:
    """Result of running a complete VHDL simulation."""
    testbench_path: Path
    return_code: int
    stdout: str
    stderr: str
    build_failed: bool = False


def strip_ansi(text: str) -> str:
    """Remove ANSI escape codes from text."""
    ansi_escape = re.compile(r'\x1b\[[0-9;]*m')
    return ansi_escape.sub('', text)


def parse_report_file(report_path: Path) -> list[VhdlTestResult]:
    """
    Parse a testbench report.txt file for test results.

    Expected format:
      [TestSuite] Suite Name
      [TestCase] #1 <Test Name> PASS
      [TestCase] #2 <Test Name> FAIL
    """
    if not report_path.exists():
        return []

    text = report_path.read_text()
    pattern = re.compile(
        r'^\[TestCase\]\s+#(\d+)\s+<(.+?)>\s+(PASS|FAIL)\s*$',
        re.MULTILINE
    )

    results = []
    for match in pattern.finditer(text):
        num, name, status = match.groups()
        results.append(VhdlTestResult(
            number=int(num),
            name=name.strip(),
            passed=(status == "PASS"),
        ))

    return results


def get_reports_dir() -> Path:
    """Get the reports directory, creating it if needed."""
    reports_dir = Path(__file__).parent / "reports" / "logs"
    reports_dir.mkdir(parents=True, exist_ok=True)
    return reports_dir


def save_simulation_log(testbench_dir: Path, stdout: str, stderr: str) -> Path:
    """Save simulation output to a log file."""
    reports_dir = get_reports_dir()

    # Create a filename from the testbench path (e.g., i2c_cbor_full_test.log)
    base_dir = Path(__file__).parent
    try:
        rel_path = testbench_dir.relative_to(base_dir)
        log_name = str(rel_path).replace("/", "_").replace("\\", "_") + ".log"
    except ValueError:
        log_name = testbench_dir.name + ".log"

    log_path = reports_dir / log_name

    # Write the log with both stdout and stderr
    with open(log_path, 'w') as f:
        f.write("=" * 70 + "\n")
        f.write(f"VHDL Simulation Log: {testbench_dir}\n")
        f.write("=" * 70 + "\n\n")

        f.write("-" * 70 + "\n")
        f.write("STDOUT:\n")
        f.write("-" * 70 + "\n")
        f.write(strip_ansi(stdout) if stdout else "(empty)\n")

        if stderr:
            f.write("\n" + "-" * 70 + "\n")
            f.write("STDERR:\n")
            f.write("-" * 70 + "\n")
            f.write(strip_ansi(stderr))

    return log_path


def run_vhdl_simulation(testbench_dir: Path, timeout: int = 600) -> VhdlSimulationResult:
    """
    Build and run a VHDL simulation.

    Args:
        testbench_dir: Path to directory containing the testbench Makefile
        timeout: Maximum time to wait for simulation (seconds)

    Returns:
        VhdlSimulationResult with stdout/stderr and build status
    """
    print(f"[VHDL] Building and running testbench in {testbench_dir}")

    report_path = testbench_dir / "report.txt"
    if report_path.exists():
        report_path.unlink()

    try:
        build_result = subprocess.run(
            ["make", "run"],
            cwd=testbench_dir,
            capture_output=True,
            text=True,
            timeout=timeout
        )
    except subprocess.TimeoutExpired as e:
        stdout = (e.stdout or b"").decode(errors="replace")
        stderr = (e.stderr or b"").decode(errors="replace")
        print(f"[VHDL] TIMEOUT after {timeout}s in {testbench_dir}")
        save_simulation_log(testbench_dir, stdout, stderr)
        return VhdlSimulationResult(
            testbench_path=testbench_dir,
            return_code=-1,
            stdout=stdout,
            stderr=stderr,
            build_failed=True,
        )

    # Save the full simulation log to a file
    log_path = save_simulation_log(testbench_dir, build_result.stdout, build_result.stderr)
    print(f"[VHDL] Log saved to: {log_path}")

    # Determine if this was a build failure by checking whether report.txt
    # was generated. A non-zero return code alone does not mean a build
    # failure — the simulation itself exits non-zero when tests fail.
    report_path = testbench_dir / "report.txt"
    build_failed = build_result.returncode != 0 and not report_path.exists()

    if build_failed:
        print(f"[VHDL] Build FAILED (exit code {build_result.returncode})")
        print(f"[VHDL] stderr: {build_result.stderr[:500]}")
    else:
        print(f"[VHDL] Simulation completed (exit code {build_result.returncode})")

    return VhdlSimulationResult(
        testbench_path=testbench_dir,
        return_code=build_result.returncode,
        stdout=build_result.stdout,
        stderr=build_result.stderr,
        build_failed=build_failed,
    )


def discover_vhdl_testbenches(base_dir: Path) -> list[Path]:
    """
    Discover VHDL testbench directories, filtered by VHDL_TESTBENCHES_TO_RUN.
    """
    selected = {
        (base_dir / Path(p)).resolve()
        for p in VHDL_TESTBENCHES_TO_RUN
    }

    testbenches = []

    for makefile in base_dir.rglob("Makefile"):
        tb_dir = makefile.parent.resolve()

        if tb_dir == base_dir:
            continue

        if tb_dir.name == "src":
            continue

        src_dir = tb_dir / "src"
        if not src_dir.exists():
            continue

        if not list(src_dir.glob("*.vhd")):
            continue

        if selected and tb_dir not in selected:
            continue

        testbenches.append(tb_dir)

    missing = selected - set(testbenches)
    if missing:
        raise RuntimeError(
            "Configured VHDL testbenches not found:\n"
            + "\n".join(str(p) for p in missing)
        )

    return sorted(testbenches)


# Cache for simulation results to avoid re-running
_simulation_cache: dict[Path, VhdlSimulationResult] = {}


def get_simulation_result(testbench_dir: Path, timeout: int = 600) -> VhdlSimulationResult:
    """Get or compute simulation result (cached)."""
    if testbench_dir not in _simulation_cache:
        _simulation_cache[testbench_dir] = run_vhdl_simulation(testbench_dir, timeout)
    return _simulation_cache[testbench_dir]


def clear_simulation_cache():
    """Clear the simulation result cache."""
    _simulation_cache.clear()


# Pytest hooks and fixtures

def pytest_configure(config):
    """Register custom markers."""
    config.addinivalue_line(
        "markers", "vhdl: mark test as a VHDL simulation test"
    )


@pytest.fixture(scope="session")
def tests_dir():
    """Return the base tests directory."""
    return Path(__file__).parent


@pytest.fixture(scope="session")
def vhdl_testbenches(tests_dir):
    """Discover all VHDL testbenches."""
    return discover_vhdl_testbenches(tests_dir)


# Test collection for VHDL tests

@dataclass
class VhdlTestInfo:
    """Information about a single VHDL test for pytest."""
    testbench_path: Path
    classname: str
    test_number: Optional[int]
    test_name: Optional[str]
    passed: bool
    full_log: str


def collect_vhdl_tests() -> list[VhdlTestInfo]:
    """
    Collect all VHDL tests by running simulations and parsing report.txt.

    Test pass/fail is determined exclusively from report.txt.
    If the build fails (no report.txt produced), a single failing test
    entry is emitted for the testbench.
    """
    base_dir = Path(__file__).parent
    testbenches = discover_vhdl_testbenches(base_dir)
    all_tests = []

    for tb_path in testbenches:
        rel_path = next((p for p in VHDL_TESTBENCHES_TO_RUN if p in str(tb_path)))
        classname = rel_path.replace("/", ".")

        result = get_simulation_result(tb_path)
        full_log = strip_ansi(result.stdout)
        if result.stderr:
            full_log += "\n" + strip_ansi(result.stderr)

        if result.build_failed:
            # Build failed — no report.txt, emit a single failing entry
            all_tests.append(VhdlTestInfo(
                testbench_path=tb_path,
                classname=classname,
                test_number=None,
                test_name=None,
                passed=False,
                full_log=full_log,
            ))
            continue

        # Parse results from the report.txt generated by the simulation
        report_path = tb_path / "report.txt"
        tests = parse_report_file(report_path)

        if tests:
            for t in tests:
                all_tests.append(VhdlTestInfo(
                    testbench_path=tb_path,
                    classname=classname,
                    test_number=t.number,
                    test_name=t.name,
                    passed=t.passed,
                    full_log=full_log,
                ))
        else:
            # Simulation ran but report.txt is empty or unparseable
            all_tests.append(VhdlTestInfo(
                testbench_path=tb_path,
                classname=classname,
                test_number=None,
                test_name=None,
                passed=False,
                full_log=full_log,
            ))

    return all_tests


def pytest_generate_tests(metafunc):
    """Parametrize vhdl_test fixture with all discovered VHDL tests."""
    if "vhdl_test" in metafunc.fixturenames:
        all_tests = collect_vhdl_tests()
        metafunc.parametrize(
            "vhdl_test",
            all_tests,
            ids=[
                f"{t.classname}::{t.test_number:02d}_{t.test_name.replace(' ', '_')}"
                if t.test_name else f"{t.classname}::simulation"
                for t in all_tests
            ]
        )
