"""
VHDL testbench integration with pytest.

Produces JUnit XML with:
- classname = testbench path (e.g., "i2c_cbor.full_test") -> shows as "package" in Jenkins
- name = individual test name -> shows as test within the package
- system-out = full simulation log (saved to log files by conftest)
"""

import pytest


@pytest.mark.vhdl
def test_vhdl(vhdl_test, record_xml_attribute):
    """
    Run a single VHDL test (or whole testbench if individual tests not parsed).

    Test results come from the report.txt generated by each testbench.
    Uses record_xml_attribute to set classname and name in JUnit XML output,
    which Jenkins uses for hierarchical display.
    """
    # Build test name for JUnit XML
    if vhdl_test.test_name:
        test_name = f"test_{vhdl_test.test_number:02d}_{vhdl_test.test_name.replace(' ', '_')}"
    else:
        test_name = "simulation"

    # Set JUnit XML attributes for proper Jenkins grouping
    record_xml_attribute("classname", vhdl_test.classname)
    record_xml_attribute("name", test_name)

    # Print full simulation log to stdout so junit_logging captures it
    # into <system-out> in the JUnit XML for Jenkins to display
    if vhdl_test.full_log:
        print(vhdl_test.full_log)

    # Check if test passed
    if not vhdl_test.passed:
        if vhdl_test.test_name:
            error_msg = f"VHDL Test #{vhdl_test.test_number} FAILED: {vhdl_test.test_name}"
        else:
            # Build / simulation-level failure
            error_msg = f"VHDL simulation failed for {vhdl_test.classname}"
            if vhdl_test.full_log:
                last_lines = vhdl_test.full_log.strip().split('\n')[-10:]
                error_msg += "\n\nLast lines of log:\n"
                error_msg += "\n".join(f"  {line}" for line in last_lines)

        pytest.fail(error_msg, pytrace=False)
