vhdl-sources += si5351.pkg.vhd
vhdl-sources += si5351_config_switcher.vhd

deps += nsl_math.arith
deps += nsl_logic.bool
deps += nsl_data.bytestream
deps += nsl_data.endian
deps += nsl_bnoc.framed_transactor
deps += nsl_i2c.transactor
