target = blink
top = work.top
work-srcdir = $(SRC_DIR)/../src
target_part = LCMXO2-1200HC
target_package = TQFP144
target_package2 = TQFP144
target_speed = 6
target_arch = MachXO2
target_dir = xo2c00
target_technology = MACHXO2
target_tech = xo2c00

hwdep = lattice-machxo2
tool = diamond

all: $(target).bin

include ../../../build/build.mk
