vhdl-sources += udp.pkg.vhd
vhdl-sources += udp_receiver.vhd
vhdl-sources += udp_transmitter.vhd
vhdl-sources += udp_layer.vhd

deps += nsl_data.bytestream
deps += nsl_data.endian
deps += nsl_inet.ipv4
deps += nsl_inet.checksum
deps += nsl_bnoc.committed
