top = work.framed_spi_controller

ip-taxonomy = /Framed_Network
ip-library = framed
ip-name = spi_controller
ip-version = 1.0
ip-revision = 1
ip-display-name = Framed SPI Master controller
ip-description = SPI Bus controller

include ../packaging.mk
