target = mem_ap
top = work.topcell.top
work-srcdir = $(SRC_DIR)/src
target_part = xc6slx9
target_package = tqg144
target_speed = -2
hwdep = xilinx
tool = ise

all: mem_ap-compressed.bit

include ../../build/build.mk
