vhdl-sources += ram.pkg.vhd
vhdl-sources += axi4_mm_ram.vhd
vhdl-sources += axi4_mm_full_ram.vhd
vhdl-sources += axi4_mm_lite_ram.vhd

deps += nsl_memory.ram
deps += nsl_logic.bool
deps += nsl_logic.logic
deps += nsl_data.bytestream
deps += nsl_data.endian
deps += nsl_data.text
deps += nsl_math.arith
deps += nsl_axi.axi4_mm
