vhdl-sources += stream_dhcp.pkg.vhd
vhdl-sources += stream_dhcp_client.vhd

deps += nsl_amba.axi4_stream
deps += nsl_data.bytestream
deps += nsl_data.endian
deps += nsl_data.prbs
deps += nsl_logic.bool
deps += nsl_math.int_ext
deps += nsl_inet.mac
deps += nsl_inet.ipv4
deps += nsl_inet.stream
deps += nsl_inet.stream_ipv4
deps += nsl_inet.stream_udp
