vhdl-sources += tb.vhd
deps += nsl_memory.fifo
deps += nsl_simulation.log
deps += nsl_simulation.assertions
deps += nsl_data.text
deps += nsl_amba.axi4_stream
deps += nsl_data.prbs
deps += nsl_simulation.driver
deps += nsl_amba.stream_fifo



