vhdl-sources += receiver.pkg.vhd
vhdl-sources += receiver_tick_recovery.vhd
vhdl-sources += tick_measurer.vhd
vhdl-sources += tick_recoverer.vhd

deps += nsl_math.fixed
deps += nsl_math.arith
deps += nsl_dsp.rc
