vhdl-sources += activity.pkg.vhd
vhdl-sources += activity_monitor.vhd
vhdl-sources += activity_blinker.vhd
vhdl-sources += activity_rgb_priority_encoder.vhd

deps += nsl_math.arith
deps += nsl_sensor.priority
deps += nsl_color.rgb
