vhdl-sources += tb.vhd

deps += nsl_wishbone.wishbone
deps += nsl_wishbone.testing
deps += nsl_wishbone.crossbar
deps += nsl_wishbone.memory
deps += nsl_data.text
deps += nsl_simulation.driver
deps += nsl_simulation.assertions
