vhdl-sources += stream_routing.pkg.vhd
vhdl-sources += axi4_stream_funnel.vhd
vhdl-sources += axi4_stream_dispatch.vhd
vhdl-sources += axi4_stream_router.vhd

deps += nsl_amba.axi4_stream
deps += nsl_data.bytestream
deps += nsl_logic.bool
