vhdl-sources += cbor_transactor.pkg.vhd
vhdl-sources += axi4stream_cbor_dp_transactor.vhd
deps += nsl_coresight.swd
deps += nsl_io.io
deps += nsl_amba.axi4_stream
deps += nsl_data.cbor
deps += nsl_logic.bool
