vhdl-sources += transmitter.pkg.vhd
vhdl-sources += i2s_transmitter.vhd
vhdl-sources += i2s_transmitter_master.vhd
vhdl-sources += i2s_transmitter_slave.vhd

deps += nsl_clocking.async
deps += nsl_i2s.clock
deps += nsl_math.arith
