target = tap_test
top = work.tap_test
work-srcdir = $(SRC_DIR)/../src
target_part_name = GW1N-9C
target_part = GW1N-UV9UG256C6/I5
hwdep = gowin
tool = gowin

all: $(target).fs

include ../../../build/build.mk
