vhdl-sources += cec.pkg.vhd
vhdl-sources += cec_deserializer.vhd
vhdl-sources += cec_serializer.vhd

deps += nsl_math.timing
deps += nsl_math.arith
deps += nsl_math.int_ext
deps += nsl_io.io
deps += nsl_clocking.async
