vhdl-sources += dp.pkg.vhd
vhdl-sources += dp_transactor.vhd
vhdl-sources += dp_framed_swdp.vhd
vhdl-sources += swdp.vhd
deps += nsl_bnoc.framed
deps += nsl_coresight.swd
deps += nsl_coresight.dapbus
