top = work.routed_endpoint

ip-taxonomy = /Routed_Network
ip-library = routed
ip-name = endpoint
ip-version = 1.0
ip-revision = 1
ip-display-name = Routed endpoint
ip-description = Routed endpoint to a framed port

include ../packaging.mk
