vhdl-sources += mm_stream_adapter.pkg.vhd
vhdl-sources += axi4_mm_on_stream.vhd

deps += nsl_axi.axi4_mm
deps += nsl_axi.axi4_stream
deps += nsl_axi.stream_routing
deps += nsl_data.bytestream
deps += nsl_data.endian
deps += nsl_data.text
deps += nsl_logic.logic
deps += nsl_logic.bool
