vhdl-sources += mm_fifo.pkg.vhd
vhdl-sources += axi4_mm_a_fifo.vhd
vhdl-sources += axi4_mm_w_fifo.vhd
vhdl-sources += axi4_mm_b_fifo.vhd
vhdl-sources += axi4_mm_r_fifo.vhd
vhdl-sources += axi4_mm_fifo.vhd
vhdl-sources += axi4_mm_a_slice.vhd
vhdl-sources += axi4_mm_w_slice.vhd
vhdl-sources += axi4_mm_b_slice.vhd
vhdl-sources += axi4_mm_r_slice.vhd
vhdl-sources += axi4_mm_slice.vhd

deps += nsl_axi.axi4_mm
deps += nsl_memory.fifo
deps += nsl_logic.bool
