packages += timing
packages += burst
packages += dram
packages += sdram_io
packages += sram_io
packages += frontend
packages += sdram
packages += sram
packages += simulation

nsl_ext_ram-ghdl-flags += -Wno-hide
