packages += timing
packages += part
packages += dfi
packages += burst
packages += dram
packages += sdram_io
packages += ddr3_io
packages += sram_io
packages += frontend
packages += sdram
packages += ddr3
packages += sram
packages += simulation

nsl_ext_ram-ghdl-flags += -Wno-hide
