vhdl-sources += continuous_transport.pkg.vhd
vhdl-sources += continuous_transport_deserializer.vhd
vhdl-sources += continuous_transport_serializer.vhd
vhdl-sources += continuous_transport_deframer.vhd
vhdl-sources += continuous_transport_framer.vhd
vhdl-sources += continuous_transport_core.vhd
vhdl-sources += continuous_transport_slave.vhd

deps += nsl_bnoc.framed
deps += nsl_hwdep.jtag
deps += nsl_memory.fifo
deps += nsl_clocking.async
deps += nsl_clocking.interdomain
deps += nsl_logic.bool
