vhdl-sources += continuous_transport.pkg.vhd
vhdl-sources += continuous_transport_deserializer.vhd
vhdl-sources += continuous_transport_serializer.vhd
vhdl-sources += jtag_continuous_transport_tap.vhd
vhdl-sources += continuous_transport_slave.vhd
vhdl-sources += continuous_transport_core.vhd

deps += nsl_bnoc.framed
deps += nsl_bnoc.chunked_link
deps += nsl_hwdep.jtag
deps += nsl_memory.fifo
deps += nsl_clocking.async
deps += nsl_clocking.interdomain
deps += nsl_logic.bool
