vhdl-sources += tb.vhd

deps += nsl_bnoc.pipe
deps += nsl_bnoc.testing
deps += nsl_bnoc.axi_adapter
deps += nsl_amba.axi4_stream
deps += nsl_data.bytestream
deps += nsl_simulation.logging
deps += nsl_simulation.driver
