target = usb
top = work.main
work-srcdir = $(SRC_DIR)/../src
target_part = iCE40UP5K
target_package = SG48
target_speed =
hwdep = lattice-ice40
tool = icecube2

all: $(target).bin

include ../../../build/build.mk
