vhdl-sources += pca9555.pkg.vhd
vhdl-sources += pca9555_driver.vhd

deps += nsl_bnoc.framed
deps += nsl_bnoc.framed_transactor
deps += nsl_data.bytestream
deps += nsl_data.endian
deps += nsl_logic.bool
