vhdl-sources += random_pkt_checker.pkg.vhd
vhdl-sources += random_pkt_validator.vhd
vhdl-sources += random_pkt_generator.vhd
vhdl-sources += random_cmd_generator.vhd
vhdl-sources += random_stats_asserter.vhd

deps += nsl_logic.logic
deps += nsl_data.crc
deps += nsl_data.bytestream