vhdl-sources += tb.vhd

deps += nsl_spi.slave
deps += nsl_data.bytestream
deps += nsl_data.text
deps += nsl_simulation.driver
deps += nsl_simulation.logging
deps += nsl_simulation.assertions
deps += nsl_bnoc.framed
deps += nsl_bnoc.testing
deps += nsl_spi.testing
