packages += file_io
packages += fifo
packages += driver
packages += control
packages += test_reports
packages += logging
packages += assertions
packages += socket
packages += udp_socket
packages += tcp_socket
packages += shell

