vhdl-sources += util.vhd
vhdl-sources += gray_encoder.vhd
vhdl-sources += gray_decoder.vhd
vhdl-sources += reset_synchronizer.vhd
vhdl-sources += resync_reg.vhd
vhdl-sources += baudrate_generator.vhd

