top = work.axis_ws2812_column_driver

ip-taxonomy = /AXIS_Infrastructure
ip-library = nsl
ip-name = axis_ws2812_column_driver
ip-display-name = AXI-Stream to indexed WS2812 column controller
ip-description = AXI-Stream to indexed WS2812 column controller
ip-version = 1.0
ip-revision = 1

include ../packaging.mk
