vhdl-sources += stream_fifo.pkg.vhd
vhdl-sources += axi4_stream_fifo.vhd
vhdl-sources += axi4_stream_slice.vhd
vhdl-sources += axi4_stream_cdc.vhd

deps += nsl_memory.fifo
deps += nsl_axi.axi4_stream
deps += nsl_clocking.interdomain
