target = tap_test
top = work.tap_test
work-srcdir = $(SRC_DIR)/../src
target_part = xc6slx9
target_package = tqg144
target_speed = -2
hwdep = xilinx
tool = ise

all: $(target)-compressed.bit

include ../../../build/build.mk
