vhdl-sources += ftdi.vhd
vhdl-sources += ft245_sync_fifo_master.vhd
vhdl-sources += ft245_sync_fifo_slave.vhd
vhdl-sources += ftdi_fs_tx.vhd
vhdl-sources += ftdi_fs_rx.vhd
vhdl-sources += ftdi_fs_master.vhd
vhdl-sources += ftdi_fs_slave.vhd
deps += util.sync
