vhdl-sources += axi_apb.pkg.vhd
vhdl-sources += axi4_apb_bridge.vhd

deps += nsl_math.arith
deps += nsl_logic.bool
deps += nsl_logic.logic
deps += nsl_data.bytestream
deps += nsl_data.endian
deps += nsl_amba.axi4_mm
deps += nsl_amba.apb
