vhdl-sources += stream_ipv4.pkg.vhd
vhdl-sources += stream_ipv4_trimmer.vhd
vhdl-sources += stream_ipv4_receiver.vhd
vhdl-sources += stream_ipv4_transmitter.vhd
vhdl-sources += stream_ipv4_layer.vhd
vhdl-sources += stream_ipv4_icmp_echo.vhd

deps += nsl_amba.axi4_stream
deps += nsl_amba.stream_routing
deps += nsl_data.bytestream
deps += nsl_data.endian
deps += nsl_logic.bool
deps += nsl_math.arith
deps += nsl_math.int_ext
deps += nsl_inet.ipv4
deps += nsl_inet.stream
deps += nsl_inet.checksum
