vhdl-sources += transceiver.pkg.vhd
vhdl-sources += dvi_driver.vhd
vhdl-sources += dvi_receiver.vhd

deps += nsl_io.clock
deps += nsl_io.delay
deps += nsl_io.serdes
deps += nsl_clocking.pll
deps += nsl_clocking.async
deps += nsl_line_coding.tmds
deps += nsl_video.mode
deps += nsl_dvi.dvi
