vhdl-sources += memory.pkg.vhd
vhdl-sources += wishbone_ram_controller.vhd
vhdl-sources += wishbone_rom.vhd
vhdl-sources += wishbone_ram.vhd
vhdl-sources += wishbone_dpram.vhd

deps += nsl_memory.rom
deps += nsl_memory.ram
deps += nsl_wishbone.wishbone
deps += nsl_logic.bool
deps += nsl_data.bytestream
deps += nsl_data.endian
deps += nsl_math.arith

