vhdl-sources += usb_commands.vhd
vhdl-sources += dut.vhd
vhdl-sources += usb_stimuli.vhd
vhdl-sources += usb_fs_monitor.vhd
vhdl-sources += usb_fs_master.vhd
vhdl-sources += tb.vhd

deps += nsl_hwdep.reset
deps += nsl_clocking.async
deps += nsl_memory.fifo
deps += nsl_usb.usb
deps += nsl_usb.utmi
deps += nsl_usb.io
deps += nsl_usb.fs_phy
deps += nsl_usb.func

