vhdl-sources += ez_usb_fx2.pkg.vhd
vhdl-sources += fx2_controller.vhd
vhdl-sources += fx2_controller_fixed.vhd
vhdl-sources += fx2_controller_fixed_fast.vhd
deps += nsl_amba.axi4_stream
deps += nsl_data.bytestream
deps += nsl_logic.bool
