CONFIG_NSL_FIFO = y
CONFIG_NSL_TESTING = y

libraries = nsl testing work
testing-srcdir = ../../lib/testing
nsl-srcdir = ../../lib/nsl
work-srcdir = src

tool = ghdl
top = tb

include ../../build/build.mk

tb.vcd: input.txt
