target = rgb2ws2812
top = work.top
work-srcdir = $(SRC_DIR)/src
target_part = xc6slx9
target_package = tqg144
target_speed = -2
hwdep = xilinx
tool = ise

all: rgb2ws2812-compressed.bit

include ../../../build/build.mk
