top = work.ip_top

ip-taxonomy = /AXI
ip-library = infrastructure
ip-name = axi4lite_stream_endpoint
ip-version = 1.1
ip-revision = 2
ip-display-name = AXI4-Lite Stream endpoint
ip-description = Lite AXI-MM to AXI-Stream mapper

include ../packaging.mk
