vhdl-sources += tb.vhd
deps += nsl_simulation.driver
deps += nsl_simulation.assertions
deps += nsl_clocking.async
deps += nsl_color.rgb
deps += nsl_line_coding.tmds
deps += nsl_hdmi.encoder
deps += nsl_dvi.encoder
deps += nsl_hdmi.audio
deps += nsl_clocking.generator

