vhdl-sources += sized.pkg.vhd
vhdl-sources += sized_from_framed.vhd
vhdl-sources += sized_to_framed.vhd
vhdl-sources += sized_fifo.vhd

deps += nsl_memory.fifo
deps += nsl_bnoc.pipe
deps += nsl_bnoc.framed
