vhdl-sources += tb.vhd
deps += nsl_data.bytestream
deps += nsl_data.prbs
deps += nsl_data.text
deps += nsl_math.arith
deps += nsl_logic.bool
deps += nsl_simulation.assertions
deps += nsl_simulation.control
deps += nsl_simulation.driver
deps += nsl_simulation.logging

deps += nsl_avalon.avalon_st
