vhdl-sources += hdlc.pkg.vhd
vhdl-sources += hdlc_framer.vhd
vhdl-sources += hdlc_unframer.vhd

deps += nsl_logic.bool
deps += nsl_data.bytestream
deps += nsl_data.endian
deps += nsl_bnoc.crc
deps += nsl_bnoc.pipe
