vhdl-sources += stream_udp.pkg.vhd
vhdl-sources += stream_udp_validator.vhd
vhdl-sources += stream_udp_receiver.vhd
vhdl-sources += stream_udp_transmitter.vhd
vhdl-sources += stream_udp_layer.vhd

deps += nsl_amba.axi4_stream
deps += nsl_amba.stream_routing
deps += nsl_data.bytestream
deps += nsl_data.endian
deps += nsl_logic.bool
deps += nsl_math.arith
deps += nsl_math.int_ext
deps += nsl_inet.ipv4
deps += nsl_inet.stream
deps += nsl_inet.stream_ipv4
deps += nsl_inet.checksum
