top = work.framed_jtag_controller

ip-taxonomy = /Framed_Network
ip-library = framed
ip-name = jtag_controller
ip-version = 1.0
ip-revision = 1
ip-display-name = Framed JTAG controller
ip-description = JTAG ATE

include ../packaging.mk
