vhdl-sources += pmod_dtx2.pkg.vhd
vhdl-sources += pmod_dtx2_characters.vhd
vhdl-sources += pmod_dtx2_driver.vhd
vhdl-sources += pmod_dtx2_hex.vhd

deps += nsl_indication.seven_segment
deps += nsl_digilent.pmod
