vhdl-sources += link_monitor.pkg.vhd
vhdl-sources += link_monitor_smi.vhd
vhdl-sources += link_monitor_inband_status.vhd

deps += nsl_math.arith
deps += nsl_logic.bool
deps += nsl_clocking.interdomain
deps += nsl_bnoc.framed
deps += nsl_data.bytestream
deps += nsl_data.endian
deps += nsl_mii.link
deps += nsl_mii.flit
