top = work.framed_uart_trx

ip-taxonomy = /AXIS_Infrastructure
ip-library = bnoc
ip-name = stream_uart_trx
ip-display-name = AXI Stream UART/HDLC TRX
ip-description = AXI Stream to HDLC transport
ip-version = 1.0
ip-revision = 1

vivado-init-tcl += init.tcl

include ../packaging.mk
