vhdl-sources += stream_traffic.pkg.vhd
vhdl-sources += random_pkt_validator.vhd
vhdl-sources += random_pkt_generator.vhd
vhdl-sources += random_cmd_generator.vhd
vhdl-sources += stream_error_inserter.vhd

deps += nsl_logic.bool
deps += nsl_logic.logic
deps += nsl_amba.axi4_stream
deps += nsl_data.crc
deps += nsl_data.bytestream
deps += nsl_data.endian
deps += nsl_data.text
deps += nsl_data.prbs
