vhdl-sources += mcp4726.pkg.vhd
vhdl-sources += mcp4726_updater.vhd

deps += nsl_bnoc.framed
deps += nsl_bnoc.framed_transactor
deps += nsl_data.bytestream
deps += nsl_data.endian
deps += nsl_i2c.transactor
