vhdl-sources += rom_fixed.pkg.vhd
vhdl-sources += rom_sfixed.vhd
vhdl-sources += rom_ufixed.vhd
vhdl-sources += rom_sfixed_2p.vhd
vhdl-sources += rom_ufixed_2p.vhd

deps += nsl_memory.rom
deps += nsl_data.text
deps += nsl_math.real_ext
deps += nsl_math.arith
deps += nsl_math.fixed
