packages += clock
packages += jtag
packages += reset

ifneq ($(filter lattice-ice40,$(hwdep)),)
packages += ice40
endif

packages += uid
packages += config

ifneq ($(filter xilinx,$(hwdep)),)
packages += xadc
endif
