vhdl-sources += pcal6524.pkg.vhd
vhdl-sources += pcal6524_driver.vhd

deps += nsl_bnoc.framed
deps += nsl_bnoc.routed_transactor
deps += nsl_data.bytestream
deps += nsl_data.endian
deps += nsl_logic.bool
