vhdl-sources += shift_register.pkg.vhd
vhdl-sources += spi_shift_register.vhd
vhdl-sources += fifo_shift_register.vhd
vhdl-sources += slave_shift_register_oversampled.vhd

deps += nsl_spi.spi
deps += nsl_logic.bool
deps += nsl_data.endian
