vhdl-sources += ipv4.pkg.vhd
vhdl-sources += ipv4_layer.vhd
vhdl-sources += ipv4_receiver.vhd
vhdl-sources += ipv4_transmitter.vhd
vhdl-sources += ipv4_checksum_inserter.vhd
vhdl-sources += icmpv4.vhd

deps += nsl_math.arith
deps += nsl_logic.bool
deps += nsl_bnoc.committed
deps += nsl_memory.ram
deps += nsl_inet.checksum
deps += nsl_inet.ethernet
deps += nsl_data.bytestream
deps += nsl_data.endian
