vhdl-sources += ipv4.pkg.vhd
vhdl-sources += ipv4_layer_ethernet.vhd
vhdl-sources += ipv4_receiver.vhd
vhdl-sources += ipv4_transmitter.vhd
vhdl-sources += arp_ethernet.vhd
vhdl-sources += icmpv4.vhd
vhdl-sources += l12_resolver_fixed.vhd

deps += nsl_math.arith
deps += nsl_logic.bool
deps += nsl_bnoc.fifo
deps += nsl_bnoc.committed
deps += nsl_memory.ram
deps += nsl_data.bytestream
deps += nsl_data.endian

