vhdl-sources += axi_wrapper.pkg.vhd
vhdl-sources += axi4_stream_chunker.vhd
vhdl-sources += axi4_stream_unchunker.vhd

deps += nsl_bnoc.framed
deps += nsl_bnoc.pipe
deps += nsl_bnoc.committed
deps += nsl_bnoc.packetizer
deps += nsl_bnoc.axi_adapter
deps += nsl_bnoc.chunked_link
deps += nsl_amba.axi4_stream
deps += nsl_data.bytestream
deps += nsl_logic.bool
