vhdl-sources += tb.vhd

deps += nsl_inet.ethernet
deps += nsl_inet.ipv4
deps += nsl_data.text
deps += nsl_data.bytestream
deps += nsl_bnoc.testing
deps += nsl_simulation.logging
deps += nsl_simulation.driver
deps += nsl_simulation.assertions
