vhdl-sources += link.pkg.vhd
vhdl-sources += link_clock_driver.vhd
vhdl-sources += link_cmd_engine.vhd
vhdl-sources += link_dat_engine.vhd

deps += nsl_data.crc
deps += nsl_data.bytestream
deps += nsl_io.io
deps += nsl_logic.bool
deps += nsl_sdio.sdio
