top = work.ip_top

ip-taxonomy = /Infrastructure
ip-library = infrastructure
ip-name = Asynchronous_Fifo
ip-version = 1.0
ip-revision = 1
ip-display-name = Dual-clock fifo
ip-description = Fifo

include ../packaging.mk
