vhdl-sources += simulation.pkg.vhd
vhdl-sources += sdram_model.vhd
vhdl-sources += ddr3_model.vhd
vhdl-sources += sram_model.vhd
deps += nsl_ext_ram.timing
deps += nsl_ext_ram.dfi
deps += nsl_data.bytestream
deps += nsl_io.io
