vhdl-sources += pmod_lcd_096.pkg.vhd
vhdl-sources += pmod_lcd_096_io_driver.vhd
vhdl-sources += pmod_lcd_096_driver.vhd

deps += nsl_spi.spi
deps += nsl_color.rgb
deps += nsl_data.bytestream
deps += nsl_digilent.pmod
deps += nsl_sitronix.st7735
