top = work.i2c_glitch_filter

ip-taxonomy = /Infrastructure
ip-library = infrastructure
ip-name = i2c_input_deglitcher
ip-version = 1.0
ip-revision = 1
ip-display-name = I2C glitch filter
ip-description = I2C glitch filter with implicit clocking

include ../packaging.mk
