vhdl-sources += slave.pkg.vhd
vhdl-sources += smi_c22_slave_axi_master.vhd
vhdl-sources += smi_c22_slave_regmap.vhd

deps += nsl_clocking.async
deps += nsl_data.bytestream
deps += nsl_data.endian
deps += nsl_smi.smi
deps += nsl_amba.axi4_mm
