vhdl-sources += stream.pkg.vhd
vhdl-sources += spdif_stream_receiver.vhd
vhdl-sources += spdif_stream_transmitter.vhd

deps += nsl_amba.axi4_stream
deps += nsl_audio.pcm
deps += nsl_audio.pcm_stream
deps += nsl_audio.metadata
deps += nsl_spdif.framer
deps += nsl_synthesis.assertion
