vhdl-sources += fifo_transport.pkg.vhd
vhdl-sources += spi_fifo_transport_master.vhd
vhdl-sources += spi_fifo_transport_slave.vhd

deps += nsl_spi.spi
deps += nsl_spi.shift_register
deps += nsl_clocking.interdomain
