top = work.ip_top

ip-taxonomy = /AXI
ip-library = clocking
ip-name = axi4lite_clock_measurer
ip-version = 1.0
ip-revision = 1
ip-display-name = AXI4-Lite Clock rate measurer
ip-description = Clock monitor

ip-packaging-scripts += ports.tcl

include ../packaging.mk
