vhdl-sources += tb.vhd
deps += nsl_math.fixed
deps += nsl_math.float
deps += nsl_data.text
deps += nsl_data.binary_io
deps += nsl_data.endian
deps += nsl_data.bytestream
deps += nsl_simulation.logging
