subdirs-$(CONFIG_NSL_NOC) += noc
subdirs-$(CONFIG_NSL_SWD) += swd
subdirs-$(CONFIG_NSL_FIFO) += fifo
subdirs-$(CONFIG_NSL_NOC) += noc
subdirs-$(CONFIG_NSL_FTDI) += ftdi
subdirs-$(CONFIG_NSL_LOGIC_ANALYZER) += logic_analyzer
subdirs-$(CONFIG_NSL_TESTING) += testing
subdirs += util
vhdl-sources += type.vhd

