vhdl-sources += sspi.pkg.vhd
vhdl-sources += sspi_loader.vhd

deps += nsl_bnoc.framed
deps += nsl_io.io
deps += nsl_math.timing
deps += nsl_math.arith
deps += nsl_data.bytestream
deps += nsl_logic.bool
deps += nsl_math.int_ext

