vhdl-sources += tb.vhd
deps += nsl_line_coding.ibm_8b10b
deps += nsl_simulation.assertions
deps += nsl_simulation.logging
deps += nsl_data.text
deps += nsl_logic.bool
deps += nsl_logic.logic
deps += nsl_simulation.control
