vhdl-sources += sie.pkg.vhd 
vhdl-sources += sie_management.vhd    
vhdl-sources += sie_packet.vhd  
vhdl-sources += sie_transfer.vhd
vhdl-sources += sie_transfer_router.vhd
vhdl-sources += sie_ep0.vhd
vhdl-sources += sie_descriptor.vhd

deps += nsl_clocking.async
deps += nsl_logic.bool
deps += nsl_math.arith
deps += nsl_memory.rom
deps += nsl_memory.fifo
deps += nsl_usb.descriptor
deps += nsl_usb.usb
deps += nsl_usb.utmi
