vhdl-sources += ibm_8b10b.pkg.vhd
vhdl-sources += ibm_8b10b_logic.pkg.vhd
vhdl-sources += ibm_8b10b_table.pkg.vhd
vhdl-sources += ibm_8b10b_spec.pkg.vhd
vhdl-sources += ibm_8b10b_decoder.vhd
vhdl-sources += ibm_8b10b_encoder.vhd

deps += nsl_logic.bool
deps += nsl_logic.logic
deps += nsl_data.bytestream
deps += nsl_data.text
deps += nsl_memory.lut_sync

