vhdl-sources += audio.pkg.vhd
vhdl-sources += hdmi_spdif_di_encoder.vhd
vhdl-sources += hdmi_spdif_cts_counter.vhd
deps += nsl_hdmi.hdmi
deps += nsl_spdif.blocker
deps += nsl_logic.logic
deps += nsl_data.bytestream
deps += nsl_data.endian
