vhdl-sources += mau_10baset.pkg.vhd
vhdl-sources += mau_10baset_mau.vhd
vhdl-sources += mau_10baset_tx.vhd
vhdl-sources += mau_10baset_rx.vhd
vhdl-sources += mau_10baset_link_monitor.vhd

deps += nsl_mii.flit
deps += nsl_line_coding.manchester
deps += nsl_clocking.async
deps += nsl_math.arith
deps += nsl_logic.bool
deps += nsl_data.bytestream
