library ieee;
use ieee.std_logic_1164.all;

library nsl_mii;

package mau_10baset is

  -- 10BASE-T Medium Attachment Unit implemented in plain fabric
  -- logic, for direct connection of FPGA pins to ethernet magnetics,
  -- without any external Phy.
  --
  -- Electrical setup:
  -- * TD pair is driven pseudo-differentially by tx_p_o / tx_n_o
  --   through the magnetics, gated by tx_en_o.  While tx_en_o is
  --   low, both pads must be released (high-Z): magnetics windings
  --   usually share their center tap, an actively driven idle level
  --   would clamp the bias network of the whole magnetics, receive
  --   side included.
  -- * RD pair feeds a differential input buffer used as a comparator
  --   (e.g. nsl_io.pad.pad_diff_input), whose single-ended output
  --   comes back as rx_i, asynchronous to clock_i.  Pair common mode
  --   must be biased within the input buffer common mode range,
  --   e.g. with a weak pull-up on one pin and a weak pull-down on
  --   another pin of a winding sharing the same magnetics center tap.
  --
  -- The MAU transmits Normal Link Pulses when idle.  A link partner
  -- with autonegotiation enabled falls back to 10BASE-T half-duplex
  -- through parallel detection.  RD pair polarity is resolved
  -- automatically from received frame preamble / SFD, wiring order of
  -- the RD pair legs is a don't-care.
  --
  -- MAC-side interface is the mii flit interface.  Frames on flit_i
  -- must include preamble and SFD (as generated by
  -- nsl_mii.flit.mii_flit_from_committed / mii_flit_from_axi4_stream).
  -- Frames on flit_o include preamble and SFD (as expected by
  -- nsl_mii.flit.mii_flit_to_committed / mii_flit_to_axi4_stream).
  --
  -- This is a half-duplex medium.  The MAU runs the CSMA/CD
  -- procedure on its own: it defers to receive carrier before
  -- starting a frame, detects collisions, jams, backs off and
  -- retransmits.  Because of this, the flit interface is not paced
  -- at a constant one byte per byte time: ready_o is withheld while
  -- the MAU defers, and a frame consumed from the flit interface may
  -- be retransmitted on the line several times.  Carrier sense and
  -- collision are still exposed for a MAC that wants them.

  -- Complete MAU.  Component may not be named after the package, a
  -- package and an entity cannot share a name in a given library.
  component mau_10baset_mau is
    generic (
      -- Must be a multiple of 20 MHz, at least 100 MHz.
      clock_i_hz_c : natural;
      -- Whether receive activity during transmission is a collision.
      -- A receive path with no amplitude squelch may pick up this
      -- station's own transmission through the magnetics, which reads
      -- as a permanent collision; clear this there.  Deference is
      -- unaffected and still keeps the two directions apart.
      collision_detect_c : boolean := true;
      -- Divides link pulse period and link integrity timers, for
      -- simulation only.  Keep 1 for synthesis.
      slow_timer_div_c : natural := 1
      );
    port (
      clock_i : in std_ulogic;
      reset_n_i : in std_ulogic;

      rx_i : in std_ulogic;
      tx_p_o : out std_ulogic;
      tx_n_o : out std_ulogic;
      tx_en_o : out std_ulogic;

      flit_i : in nsl_mii.flit.mii_flit_t;
      ready_o : out std_ulogic;

      flit_o : out nsl_mii.flit.mii_flit_t;
      valid_o : out std_ulogic;

      link_up_o : out std_ulogic;
      polarity_inverted_o : out std_ulogic;
      crs_o : out std_ulogic;
      col_o : out std_ulogic;

      -- Single cycle strobes, see mau_10baset_tx.
      collision_o : out std_ulogic;
      late_collision_o : out std_ulogic;
      excessive_collision_o : out std_ulogic
      );
  end component;

  -- Frame serializer and line driver: manchester-encodes MAC frames,
  -- appends TP_IDL end-of-frame marker, emits Normal Link Pulses
  -- while idle.
  --
  -- Runs the half-duplex CSMA/CD procedure: a frame is only started
  -- once carrier_i has been low for one inter-frame gap, carrier_i
  -- rising during transmission is a collision, which triggers a jam
  -- sequence then, for a collision within the slot time, a binary
  -- exponential backoff and a retransmission of the frame from its
  -- first byte.  Retransmission is served from an internal replay
  -- buffer, the flit interface never sees it.  After 16 collisions
  -- or on a collision past the slot time, the frame is abandoned:
  -- its remaining flits are consumed and discarded.
  --
  -- ready_o strobes once per byte time, except while the MAU defers
  -- to the medium or waits out a backoff, where it does not strobe
  -- at all.  The flit source must simply wait.
  component mau_10baset_tx is
    generic (
      clock_i_hz_c : natural;
      collision_detect_c : boolean := true;
      slow_timer_div_c : natural := 1
      );
    port (
      clock_i : in std_ulogic;
      reset_n_i : in std_ulogic;

      flit_i : in nsl_mii.flit.mii_flit_t;
      ready_o : out std_ulogic;

      carrier_i : in std_ulogic;

      transmitting_o : out std_ulogic;

      -- Strobes on every detected collision.
      collision_o : out std_ulogic;
      -- Strobes on a collision detected at or after the slot time.
      late_collision_o : out std_ulogic;
      -- Strobes when a frame is abandoned after 16 collisions.
      excessive_collision_o : out std_ulogic;

      tx_p_o : out std_ulogic;
      tx_n_o : out std_ulogic;
      tx_en_o : out std_ulogic
      );
  end component;

  -- Line receiver: synchronizes and deglitches the comparator
  -- output, recovers bits, aligns on SFD with automatic polarity
  -- resolution, emits frame flits.  Also classifies isolated link
  -- pulses for the link monitor.
  component mau_10baset_rx is
    generic (
      clock_i_hz_c : natural
      );
    port (
      clock_i : in std_ulogic;
      reset_n_i : in std_ulogic;

      rx_i : in std_ulogic;

      flit_o : out nsl_mii.flit.mii_flit_t;
      valid_o : out std_ulogic;

      carrier_o : out std_ulogic;
      -- Strobes on reception of a plausible normal link pulse.
      link_pulse_o : out std_ulogic;
      -- Strobes on reception of a frame with a valid SFD.
      frame_o : out std_ulogic;
      polarity_inverted_o : out std_ulogic
      );
  end component;

  -- 802.3 link integrity function: link goes up after enough
  -- correctly-spaced link pulses (or a received frame), goes down on
  -- receive activity timeout.
  component mau_10baset_link_monitor is
    generic (
      clock_i_hz_c : natural;
      slow_timer_div_c : natural := 1
      );
    port (
      clock_i : in std_ulogic;
      reset_n_i : in std_ulogic;

      link_pulse_i : in std_ulogic;
      frame_i : in std_ulogic;

      link_up_o : out std_ulogic
      );
  end component;

end package mau_10baset;
