vhdl-sources += sync.pkg.vhd
vhdl-sources += sync_reg.vhd
vhdl-sources += sync_deglitcher.vhd
vhdl-sources += sync_rising_edge.vhd
vhdl-sources += sync_input.vhd
vhdl-sources += sync_multi_resetn.vhd
vhdl-sources += sync_cross_counter.vhd
deps += util.gray
