vhdl-sources += io.pkg.vhd
vhdl-sources += io_en_slv_driver.vhd
vhdl-sources += io_io_dir_driver.vhd
vhdl-sources += io_io_dir_in_driver.vhd
vhdl-sources += io_std_logic_driver.vhd
vhdl-sources += od_std_logic_driver.vhd
