top = work.framed_i2c_controller

ip-taxonomy = /Framed_Network
ip-library = framed
ip-name = i2c_controller
ip-version = 1.0
ip-revision = 1
ip-display-name = Framed I2C Master controller
ip-description = I2C Bus controller

include ../packaging.mk
