vhdl-sources += switching.pkg.vhd
vhdl-sources += switching_mac_table.vhd
vhdl-sources += switching_ingress.vhd
vhdl-sources += switching_fabric.vhd
vhdl-sources += switching_bridge.vhd

deps += nsl_amba.axi4_stream
deps += nsl_amba.stream_fifo
deps += nsl_amba.stream_fifo
deps += nsl_data.bytestream
deps += nsl_data.crc
deps += nsl_data.endian
deps += nsl_inet.mac
deps += nsl_logic.bool
deps += nsl_math.arith
deps += nsl_memory.ram
deps += nsl_memory.streamer
