top = work.phc_pps_flat

ip-taxonomy = /PrecisionTiming
ip-library = nsl
ip-name = precision_time_pps_output
ip-display-name = Precision time PPS output
ip-description = Timestamp network PPS generator
ip-version = 1.0
ip-revision = 1

include ../packaging.mk
