vhdl-sources += tb.vhd

deps += nsl_simulation.assertions
deps += nsl_simulation.logging
deps += nsl_simulation.driver
deps += nsl_math.fixed
deps += nsl_math.timing
deps += nsl_time.clock
deps += nsl_time.pps
