vhdl-sources += dram.pkg.vhd
vhdl-sources += dram_core.vhd
deps += nsl_ext_ram.timing
deps += nsl_ext_ram.dfi
deps += nsl_ext_ram.burst
deps += nsl_data.bytestream
deps += nsl_math.arith
deps += nsl_logic.bool
