vhdl-sources += interdomain.pkg.vhd
vhdl-sources += interdomain_fifo_slice.vhd
vhdl-sources += interdomain_reg.vhd
vhdl-sources += interdomain_counter.vhd
vhdl-sources += interdomain_static_reg.vhd
deps += nsl_math.arith
deps += nsl_math.gray
deps += nsl_clocking.intradomain
