vhdl-sources += octaver.pkg.vhd
vhdl-sources += pcm_octaver.vhd

deps += nsl_amba.axi4_stream
deps += nsl_audio.pcm
deps += nsl_audio.pcm_stream
deps += nsl_math.fixed
deps += nsl_synthesis.assertion
