vhdl-sources += fs_phy.pkg.vhd
vhdl-sources += fs_utmi8_phy.vhd
vhdl-sources += fs_utmi8_tx_phy.vhd
vhdl-sources += fs_utmi8_rx_phy.vhd

deps += nsl_usb.usb
deps += nsl_usb.utmi
deps += nsl_data.bytestream
