vhdl-sources += tb.vhd

deps += nsl_amba.axi4_stream
deps += nsl_amba.stream_traffic
deps += nsl_data.bytestream
deps += nsl_data.text
deps += nsl_simulation.assertions
deps += nsl_simulation.driver
deps += nsl_simulation.logging
