set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 2 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 66 [current_design]

set_property CFGBVS GND [current_design]
set_property CONFIG_VOLTAGE 1.8 [current_design]
#set_property INTERNAL_VREF 0.9 [get_iobanks 33]
#set_property INTERNAL_VREF 0.9 [get_iobanks 34]

# Bank 34, Using Target VREF, 0.8-3.3V
set_property PACKAGE_PIN P5 [get_ports {data_i[0]}]
set_property PACKAGE_PIN M5 [get_ports {data_i[1]}]
set_property PACKAGE_PIN N4 [get_ports {data_i[2]}]
set_property PACKAGE_PIN P3 [get_ports {data_i[3]}]
set_property PACKAGE_PIN R3 [get_ports {data_i[4]}]
set_property PACKAGE_PIN N3 [get_ports {data_i[5]}]
set_property PACKAGE_PIN M4 [get_ports {data_i[6]}]
set_property PACKAGE_PIN L5 [get_ports {data_i[7]}]
set_property PACKAGE_PIN M1 [get_ports {data_i[8]}]
set_property PACKAGE_PIN L4 [get_ports {data_i[9]}]
set_property -dict {IOSTANDARD LVCMOS33 SLEW SLOW DRIVE 4} [get_ports {data_i*}]

# Bank 14
set_property PACKAGE_PIN N14 [get_ports clock_i]
set_property IOSTANDARD LVCMOS18 [get_ports {clock_i}]

set_property PACKAGE_PIN P14 [get_ports {data_o[0]}]
set_property PACKAGE_PIN P15 [get_ports {data_o[1]}]
set_property PACKAGE_PIN P16 [get_ports {data_o[2]}]
set_property PACKAGE_PIN N12 [get_ports {data_o[3]}]
set_property PACKAGE_PIN N13 [get_ports {data_o[4]}]
set_property PACKAGE_PIN M16 [get_ports {data_o[5]}]
set_property PACKAGE_PIN N16 [get_ports {data_o[6]}]
set_property PACKAGE_PIN R15 [get_ports {data_o[7]}]
set_property PACKAGE_PIN P13 [get_ports {control_o}]
set_property PACKAGE_PIN T12 [get_ports {code_error_o}]
set_property PACKAGE_PIN R13 [get_ports {disparity_error_o}]
set_property PACKAGE_PIN T13 [get_ports {phy_reset_n_o}]
set_property IOSTANDARD LVCMOS18 [get_ports {*_o*}]
