#!/usr/bin/env python3

from nsl.fifo import FifoFile

import sys
import random

if __name__ == "__main__":
    f = FifoFile(sys.argv[1], 8)

    random.seed(0xdeadbeef)

    data = [random.randint(0, 255) for i in range(2048)]

    output = sys.argv[1].startswith("in")

    if output:
        random.seed(random.randint(0, 1<<16))

    burst = 0
    for d in data:
        if not burst:
            burst = random.randint(1, 16)
        burst -= 1
        f.put(d, 0xff, 0 if burst else random.randint(0, 8))
