vhdl-sources += source.pkg.vhd
vhdl-sources += spi_committed_source.vhd
vhdl-sources += spi_pipe_source.vhd

deps += nsl_math.arith
deps += nsl_data.bytestream
deps += nsl_bnoc.framed
deps += nsl_bnoc.committed
deps += nsl_memory.ram
deps += nsl_spi.spi
