vhdl-sources += axi4_stream_adapter.pkg.vhd
vhdl-sources += axi4_stream_to_avalon_st.vhd
vhdl-sources += avalon_st_to_axi4_stream.vhd

deps += nsl_logic.bool
deps += nsl_data.bytestream
deps += nsl_avalon.avalon_st
deps += nsl_amba.axi4_stream
