vhdl-sources += slave.pkg.vhd
vhdl-sources += spi_memory_controller.vhd
vhdl-sources += spi_framed_gateway.vhd
vhdl-sources += spi_framed_sink.vhd
vhdl-sources += spi_committed_sink.vhd

deps += nsl_data.bytestream
deps += nsl_data.endian
deps += nsl_logic.bool
deps += nsl_bnoc.sized
deps += nsl_bnoc.framed
deps += nsl_memory.fifo
deps += nsl_spi.spi
deps += nsl_spi.shift_register
