vhdl-sources += slave.pkg.vhd
vhdl-sources += spi_memory_controller.vhd
vhdl-sources += spi_framed_gateway.vhd
deps += nsl_bnoc.sized
deps += nsl_bnoc.framed
deps += nsl_memory.fifo
deps += nsl_spi.spi
deps += nsl_spi.shift_register
