tb += address
tb += apb_ram
tb += apb_regmap
tb += apb_dispatch
tb += axi4_mm_transactor
tb += axi4_apb_bridge
tb += axi4_apb_bridge_dispatch
tb += axi4_mm_cdc
tb += axi4_mm_lite_ram
tb += axi4_mm_lite_regmap
tb += axi4_mm_lite_stream_endpoint
tb += axi4_mm_on_stream
tb += axi4_mm_ram
tb += axi4_mm_types
tb += axi4_stream_cdc
tb += axi4_stream_fifo
tb += axi4_stream_flusher
tb += axi4_stream_narrower
tb += axi4_stream_types
tb += axi4_stream_widener
tb += axi4_stream_buffer
tb += axi4_stream_buffer_io
tb += axi4_stream_buffer_align
tb += axi4_stream_buffer_short
tb += axi4_stream_random_pkt_checker

include ../subdir.mk
