vhdl-sources += metadata.pkg.vhd
vhdl-sources += pcm_metadata_extract.vhd
vhdl-sources += pcm_metadata_merge.vhd

deps += nsl_amba.axi4_stream
deps += nsl_audio.pcm
deps += nsl_audio.pcm_stream
deps += nsl_synthesis.assertion
