vhdl-sources += pmod_oled_rgb.pkg.vhd
vhdl-sources += pmod_oled_rgb_io_driver.vhd
vhdl-sources += pmod_oled_rgb_driver.vhd

deps += nsl_spi.spi
deps += nsl_color.rgb
deps += nsl_digilent.pmod
deps += nsl_solomonsystech.ssd1331
