vhdl-sources += stream_endpoint.pkg.vhd
vhdl-sources += axi4_stream_endpoint_lite.vhd

deps += nsl_math.arith
deps += nsl_logic.bool
deps += nsl_logic.logic
deps += nsl_data.bytestream
deps += nsl_data.endian
deps += nsl_axi.axi4_mm
deps += nsl_axi.axi4_stream
