top = work.phc_main_flat

ip-taxonomy = /PrecisionTiming
ip-library = nsl
ip-name = precision_time_clock
ip-display-name = Precision time clock
ip-description = Module suitable for Linux PTP hardware clock API
ip-version = 1.0
ip-revision = 1

include ../packaging.mk
