vhdl-sources += stream_host.pkg.vhd
vhdl-sources += stream_ipv4_host.vhd

deps += nsl_amba.axi4_stream
deps += nsl_data.bytestream
deps += nsl_logic.bool
deps += nsl_math.int_ext
deps += nsl_inet.mac
deps += nsl_inet.ipv4
deps += nsl_inet.stream
deps += nsl_inet.stream_mac
deps += nsl_inet.stream_ethernet
deps += nsl_inet.stream_ipv4
deps += nsl_inet.stream_udp
deps += nsl_inet.stream_resolver
deps += nsl_inet.stream_arp
