vhdl-sources += transactor.pkg.vhd
vhdl-sources += dp_transactor.vhd
vhdl-sources += dp_framed_transactor.vhd
deps += nsl_bnoc.framed
deps += nsl_io.io
deps += nsl_coresight.swd
deps += nsl_event.tick
