top = work.framed_swd_controller

ip-taxonomy = /Framed_Network
ip-library = framed
ip-name = swd_controller
ip-version = 1.0
ip-revision = 1
ip-display-name = Framed SWD controller
ip-description = SWD DAP controller

include ../packaging.mk
