vhdl-sources += committed.pkg.vhd
vhdl-sources += committed_filter.vhd
vhdl-sources += committed_dispatch.vhd
vhdl-sources += committed_funnel.vhd
vhdl-sources += committed_fifo.vhd

deps += nsl_memory.fifo
deps += nsl_bnoc.framed
