vhdl-sources += fifo.pkg.vhd
vhdl-sources += fifo_counter_checker.vhd
vhdl-sources += fifo_counter_generator.vhd
vhdl-sources += fifo_sink.vhd
vhdl-sources += fifo_file_reader.vhd
vhdl-sources += fifo_file_checker.vhd
vhdl-sources += fifo_delay.vhd
vhdl-sources += fifo_bytestream_reader.vhd
vhdl-sources += fifo_bytestream_writer.vhd

deps += nsl_simulation.file_io
deps += nsl_data.bytestream
deps += nsl_data.binary_io
deps += nsl_simulation.assertions
deps += nsl_simulation.logging
