vhdl-sources += tb.vhd
deps += nsl_data.bytestream
deps += nsl_data.endian
deps += nsl_data.crc
deps += nsl_data.text
deps += nsl_simulation.assertions
deps += nsl_simulation.driver
deps += nsl_simulation.logging
deps += nsl_memory.fifo

deps += nsl_amba.random_pkt_checker
deps += nsl_amba.axi4_stream
deps += nsl_amba.stream_crc

