vhdl-sources += stream_l2.pkg.vhd
vhdl-sources += ptp_l2_slave.vhd
vhdl-sources += ptp_l2_master.vhd

deps += nsl_amba.axi4_stream
deps += nsl_data.bytestream
deps += nsl_data.endian
deps += nsl_logic.bool
deps += nsl_math.int_ext
deps += nsl_inet.mac
deps += nsl_inet.stream
deps += nsl_inet.stream_ethernet
deps += nsl_mii.timestamping
deps += nsl_time.timestamp
deps += nsl_ptp.ptp
