top = work.swd_axi4lite_master

ip-taxonomy = /Sideband
ip-library = sideband
ip-name = swd_axi4lite_master
ip-version = 1.0
ip-revision = 1
ip-display-name = SWD to AXI4-Lite bridge
ip-description = SWD and Mem-AP controller

include ../packaging.mk
