vhdl-sources += routed.pkg.vhd
vhdl-sources += routed_endpoint.vhd
vhdl-sources += routed_framed_gateway.vhd
vhdl-sources += routed_gateway.vhd
vhdl-sources += routed_router_inbound.vhd
vhdl-sources += routed_router_outbound.vhd
vhdl-sources += routed_router.vhd
vhdl-sources += routed_entry.vhd
vhdl-sources += routed_exit.vhd

deps += nsl_memory.ram
deps += nsl_bnoc.framed
