vhdl-sources += routed.pkg.vhd
vhdl-sources += routed_endpoint.vhd
vhdl-sources += routed_gateway.vhd
vhdl-sources += routed_router_inbound.vhd
vhdl-sources += routed_router_outbound.vhd
vhdl-sources += routed_router.vhd

deps += nsl_bnoc.framed
deps += hwdep.ram
