vhdl-sources += transactor.pkg.vhd
vhdl-sources += spi_framed_transactor.vhd
vhdl-sources += spi_muxed_transactor.vhd
deps += nsl_bnoc.framed
deps += nsl_data.bytestream
deps += nsl_logic.bool
deps += nsl_spi.spi
