vhdl-sources += pattern.pkg.vhd
vhdl-sources += rgb_color_bars.vhd
vhdl-sources += ycbcr_color_bars.vhd

deps += nsl_color.rgb
deps += nsl_color.ycbcr
deps += nsl_video.mode
deps += nsl_video.pixel_stream
deps += nsl_video.raster
deps += nsl_synthesis.assertion
