vhdl-sources += crc.pkg.vhd
vhdl-sources += crc_committed_adder.vhd
vhdl-sources += crc_committed_checker.vhd

deps += nsl_math.arith
deps += nsl_bnoc.committed
deps += nsl_data.bytestream
deps += nsl_data.crc
deps += nsl_logic.bool
