vhdl-sources += packer.pkg.vhd
vhdl-sources += axi4_mm_lite_slave_packer.vhd
vhdl-sources += axi4_mm_lite_master_packer.vhd
vhdl-sources += axi4_mm_slave_packer.vhd
vhdl-sources += axi4_mm_master_packer.vhd
vhdl-sources += axi4_stream_slave_packer.vhd
vhdl-sources += axi4_stream_master_packer.vhd

deps += nsl_amba.axi4_mm
deps += nsl_amba.axi4_stream
deps += nsl_logic.bool
