vhdl-sources += fpga_io.vhd

constraint-sources += ../../../pinout/leds.xdc
constraint-sources += ../../../pinout/buttons.xdc
constraint-sources += ../../../pinout/clk100.xdc
constraint-sources += ../../../pinout/ethernet.xdc
constraint-sources += ../../../pinout/uart.xdc

deps += top.func
deps += nsl_hwdep.reset
deps += nsl_smi.smi
deps += nsl_clocking.pll
deps += nsl_io.clock

