vhdl-sources += testing.pkg.vhd
vhdl-sources += framed_file_reader.vhd
vhdl-sources += framed_file_checker.vhd
vhdl-sources += sized_file_reader.vhd
vhdl-sources += sized_file_checker.vhd
deps += testing.fifo
deps += nsl_bnoc.framed
deps += nsl_bnoc.sized
