vhdl-sources += is31fl3731.pkg.vhd
vhdl-sources += is31fl3731_driver.vhd

deps += nsl_bnoc.framed
deps += nsl_bnoc.framed_transactor
deps += nsl_data.bytestream
deps += nsl_data.endian
deps += nsl_i2c.transactor
