vhdl-sources += chunked_link.pkg.vhd
vhdl-sources += spi_chunked_link_slave.vhd

deps += nsl_bnoc.framed
deps += nsl_bnoc.chunked_link
deps += nsl_spi.spi
deps += nsl_spi.shift_register
deps += nsl_memory.fifo
deps += nsl_data.bytestream
