vhdl-sources += trigonometry.pkg.vhd
vhdl-sources += rect_table.vhd
vhdl-sources += sinus_stream.vhd

deps += nsl_memory.rom
deps += nsl_math.fixed
deps += nsl_data.bytestream
deps += nsl_simulation.logging
