vhdl-sources += stream_meta.pkg.vhd
vhdl-sources += axi4_stream_meta_packer.vhd
vhdl-sources += axi4_stream_meta_unpacker.vhd

deps += nsl_amba.axi4_stream
deps += nsl_data.bytestream
deps += nsl_data.endian
deps += nsl_logic.bool
