vhdl-sources += stream_sized.pkg.vhd
vhdl-sources += axi4_stream_sized_framing_1b.vhd
vhdl-sources += axi4_stream_sized_deframing_1b.vhd
vhdl-sources += axi4_stream_sized_to_framed.vhd
vhdl-sources += axi4_stream_sized_from_framed.vhd

deps += nsl_amba.axi4_stream
deps += nsl_amba.stream_fifo
deps += nsl_data.bytestream
deps += nsl_data.endian
