vhdl-sources += stream_sized.pkg.vhd
vhdl-sources += axi4_stream_sized_framing_1b.vhd
vhdl-sources += axi4_stream_sized_deframing_1b.vhd
vhdl-sources += axi4_stream_sized_framing.vhd
vhdl-sources += axi4_stream_sized_deframing.vhd
vhdl-sources += axi4_stream_sized_deframing_1b_to_nb.vhd

deps += nsl_amba.axi4_stream
deps += nsl_amba.stream_fifo
deps += nsl_data.bytestream
deps += nsl_data.endian
