vhdl-sources += tick.pkg.vhd
vhdl-sources += tick_divisor.vhd
vhdl-sources += tick_extractor_clock.vhd
vhdl-sources += tick_oscillator.vhd
vhdl-sources += tick_extractor_self_clocking.vhd
vhdl-sources += tick_generator.vhd
vhdl-sources += tick_generator_integer.vhd
vhdl-sources += tick_measurer.vhd
vhdl-sources += tick_pll.vhd
vhdl-sources += tick_scaler_l2.vhd

deps += nsl_math.arith
deps += nsl_math.fixed
deps += nsl_clocking.async
deps += nsl_dsp.rc
