top = work.routed_router

ip-taxonomy = /Routed_Network
ip-library = routed
ip-name = router
ip-version = 1.0
ip-revision = 1
ip-display-name = Routed router
ip-description = Routed router with explicit routing table

ip-packaging-scripts += ports.tcl

include ../packaging.mk
