vhdl-sources += transactor.pkg.vhd
vhdl-sources += transactor_framed_controller.vhd
vhdl-sources += framed_addressed_controller.vhd
deps += nsl_bnoc.framed
deps += nsl_i2c.i2c
deps += nsl_i2c.master
deps += nsl_data.bytestream
deps += nsl_data.endian
