vhdl-sources += axi_adapter.pkg.vhd
vhdl-sources += framed_to_axi4_stream.vhd
vhdl-sources += axi4_stream_to_framed.vhd
vhdl-sources += pipe_to_axi4_stream.vhd
vhdl-sources += axi4_stream_to_pipe.vhd

deps += nsl_bnoc.framed
deps += nsl_bnoc.pipe
deps += nsl_amba.axi4_stream
deps += nsl_data.bytestream
deps += nsl_logic.bool
