vhdl-sources += rmii.pkg.vhd
vhdl-sources += rmii_driver_resync.vhd

deps += nsl_data.bytestream
deps += nsl_clocking.distribution
deps += nsl_clocking.interdomain
deps += nsl_bnoc.committed
deps += nsl_mii.flit
