vhdl-sources += ulpi.pkg.vhd
vhdl-sources += ulpi8_line_driver.vhd
vhdl-sources += utmi8_ulpi8_converter.vhd

deps += nsl_usb.usb
deps += nsl_usb.utmi
deps += nsl_logic.bool
deps += nsl_data.bytestream
