vhdl-sources += stream_ethernet.pkg.vhd
vhdl-sources += stream_ethernet_receiver.vhd
vhdl-sources += stream_ethernet_transmitter.vhd
vhdl-sources += stream_ethernet_layer.vhd

deps += nsl_amba.axi4_stream
deps += nsl_amba.stream_routing
deps += nsl_data.bytestream
deps += nsl_data.endian
deps += nsl_inet.mac
deps += nsl_inet.stream
deps += nsl_inet.stream_mac
deps += nsl_logic.bool
deps += nsl_math.int_ext
