top = work.activity_monitor

ip-taxonomy = /Utilities
ip-library = util
ip-name = activity_monitor
ip-display-name = Signal activity monitor
ip-description = Toggles a signal when some activity happens on a wire
ip-version = 1.0
ip-revision = 1

include ../packaging.mk
