vhdl-sources += trigonometry.pkg.vhd
vhdl-sources += rect_table.vhd
vhdl-sources += rect_cordic.vhd

deps += nsl_memory.rom_fixed
deps += nsl_math.fixed
deps += nsl_math.cordic
deps += nsl_math.real_ext
deps += nsl_data.bytestream
deps += nsl_simulation.logging
