vhdl-sources += fifo_transport.pkg.vhd
vhdl-sources += jtag_fifo_transport_slave.vhd
vhdl-sources += jtag_fifo_transport_slave_tap.vhd

deps += nsl_logic.bool
deps += nsl_hwdep.jtag
deps += nsl_memory.fifo
deps += nsl_clocking.async
deps += nsl_clocking.interdomain
