vhdl-sources += fifo.vhd
vhdl-sources += fifo_counter_checker.vhd
vhdl-sources += fifo_counter_generator.vhd
vhdl-sources += fifo_sink.vhd
vhdl-sources += fifo_file_reader.vhd
vhdl-sources += fifo_file_checker.vhd
deps += nsl.fifo
