vhdl-sources += rgmii.pkg.vhd
vhdl-sources += rgmii_signal_driver.vhd
vhdl-sources += rgmii_from_framed.vhd
vhdl-sources += rgmii_to_framed.vhd

deps += nsl_math.arith
deps += nsl_hwdep.clock
deps += nsl_data.crc
deps += nsl_data.bytestream
deps += nsl_io.diff
deps += nsl_io.clock
deps += nsl_io.ddr
deps += nsl_clocking.intradomain
