vhdl-sources += rgmii.pkg.vhd
vhdl-sources += rgmii_signal_driver.vhd
vhdl-sources += rgmii_from_committed.vhd
vhdl-sources += rgmii_to_committed.vhd

deps += nsl_math.arith
deps += nsl_bnoc.committed
deps += nsl_hwdep.clock
deps += nsl_data.crc
deps += nsl_data.bytestream
deps += nsl_io.diff
deps += nsl_io.clock
deps += nsl_io.ddr
deps += nsl_io.delay
deps += nsl_clocking.intradomain
