vhdl-sources += effect.pkg.vhd
vhdl-sources += pcm_gain.vhd
vhdl-sources += pcm_shaper.vhd
vhdl-sources += pcm_tone.vhd

deps += nsl_amba.axi4_stream
deps += nsl_audio.pcm
deps += nsl_audio.pcm_stream
deps += nsl_data.bytestream
deps += nsl_data.endian
deps += nsl_logic.bool
deps += nsl_math.fixed
deps += nsl_memory.rom
deps += nsl_synthesis.assertion
