target = blink
top = work.top
work-srcdir = $(SRC_DIR)/../src
target_part = iCE40HX1K
target_package = TQ144
target_speed =
hwdep = lattice
tool = icecube2

all: $(target).bin

include ../../../build/build.mk
