vhdl-sources += noc.vhd
vhdl-sources += noc_router_inbound.vhd
vhdl-sources += noc_router_outbound.vhd
vhdl-sources += noc_router.vhd
vhdl-sources += noc_to_framed.vhd
vhdl-sources += noc_from_framed.vhd
deps += nsl.fifo
deps += nsl.flit
