vhdl-sources += noc.vhd
vhdl-sources += noc_router_inbound.vhd
vhdl-sources += noc_router_outbound.vhd
vhdl-sources += noc_router.vhd
vhdl-sources += noc_fifo.vhd
vhdl-sources += noc_async_fifo.vhd
vhdl-sources += noc_atomic_fifo.vhd
