vhdl-sources += stream_resolver.pkg.vhd
vhdl-sources += stream_resolver_entry.vhd
vhdl-sources += stream_resolver_arbiter.vhd
vhdl-sources += stream_resolver_static_ipv4.vhd

deps += nsl_amba.axi4_stream
deps += nsl_amba.stream_fifo
deps += nsl_data.bytestream
deps += nsl_data.endian
deps += nsl_logic.bool
deps += nsl_math.int_ext
deps += nsl_inet.mac
deps += nsl_inet.ipv4
deps += nsl_inet.stream
deps += nsl_inet.stream_ethernet
deps += nsl_inet.stream_ipv4
