vhdl-sources += usb.pkg.vhd
vhdl-sources += usb_io_driver.vhd

deps += nsl_io.io
deps += nsl_data.bytestream
deps += nsl_data.crc
deps += nsl_data.endian
deps += nsl_logic.bool
deps += nsl_math.arith
