vhdl-sources += func.pkg.vhd
vhdl-sources += ethernet_host.vhd

deps += nsl_bnoc.committed
deps += nsl_inet.ethernet
deps += nsl_inet.ipv4
deps += nsl_inet.udp
deps += nsl_inet.arp
#deps += nsl_inet.dhcp
