vhdl-sources += raster.pkg.vhd
vhdl-sources += raster_counter.vhd
vhdl-sources += raster_measurer.vhd
vhdl-sources += pixel_stream_capturer.vhd
vhdl-sources += pixel_stream_framer.vhd
vhdl-sources += pixel_stream_requester.vhd
vhdl-sources += pixel_stream_unframer.vhd
vhdl-sources += pixel_stream_decimator.vhd

deps += nsl_video.mode
deps += nsl_video.pixel_stream
deps += nsl_synthesis.assertion
