vhdl-sources += fifo.pkg.vhd

vhdl-sources += fifo_pointer.vhd
vhdl-sources += fifo_homogeneous.vhd

deps += nsl_clocking.intradomain
deps += nsl_clocking.interdomain
deps += nsl_clocking.async
deps += nsl_math.arith
deps += nsl_math.gray
deps += nsl_memory.ram
