vhdl-sources += fifo.pkg.vhd

vhdl-sources += fifo_pointer.vhd
vhdl-sources += fifo_register_slice.vhd
vhdl-sources += fifo_homogeneous.vhd
vhdl-sources += fifo_narrower.vhd
vhdl-sources += fifo_cancellable.vhd
vhdl-sources += fifo_widener.vhd
vhdl-sources += fifo_count.vhd

deps += nsl_clocking.intradomain
deps += nsl_clocking.interdomain
deps += nsl_clocking.async
deps += nsl_math.arith
deps += nsl_math.gray
deps += nsl_memory.ram
deps += nsl_logic.bool
