vhdl-sources += encoder.pkg.vhd
vhdl-sources += source_stream_encoder.vhd
vhdl-sources += dvi_10_encoder.vhd
deps += nsl_color.rgb
deps += nsl_data.bytestream
deps += nsl_line_coding.tmds
deps += nsl_math.arith
