vhdl-sources += discipline.pkg.vhd
vhdl-sources += discipline_pi_servo.vhd
vhdl-sources += discipline_clock_driver.vhd
vhdl-sources += discipline_dac_driver.vhd

deps += nsl_time.timestamp
deps += nsl_math.fixed
