vhdl-sources += discipline.pkg.vhd
vhdl-sources += discipline_pi_servo.vhd
vhdl-sources += discipline_clock_driver.vhd
vhdl-sources += discipline_dac_driver.vhd
vhdl-sources += discipline_step_applier.vhd
vhdl-sources += discipline_pps_source.vhd
vhdl-sources += discipline_second_setter.vhd

deps += nsl_time.timestamp
deps += nsl_math.fixed
deps += nsl_clocking.interdomain
deps += nsl_clocking.async
