vhdl-sources += sinus.pkg.vhd
vhdl-sources += sinus_stream.vhd
vhdl-sources += sinus_stream_table.vhd
vhdl-sources += sinus_stream_cordic.vhd

deps += nsl_memory.rom_fixed
deps += nsl_math.fixed
deps += nsl_math.arith
deps += nsl_math.cordic
