vhdl-sources += mac.pkg.vhd
vhdl-sources += mac_receiver.vhd
vhdl-sources += mac_transmitter.vhd
vhdl-sources += mac_router.vhd

deps += nsl_logic.bool
deps += nsl_data.bytestream
deps += nsl_data.crc
deps += nsl_data.endian
deps += nsl_data.text
deps += nsl_bnoc.framed
deps += nsl_bnoc.crc
deps += nsl_bnoc.committed
deps += nsl_math.arith
