vhdl-sources += pmod.pkg.vhd
vhdl-sources += pmod_type2_driver.vhd
vhdl-sources += pmod_type2a_driver.vhd
vhdl-sources += pmod_type6_driver.vhd

deps += nsl_io.io
deps += nsl_spi.spi
deps += nsl_i2c.i2c
