vhdl-sources += tb.vhd

deps += nsl_simulation.assertions
deps += nsl_simulation.logging
deps += nsl_simulation.driver
deps += nsl_amba.axi4_stream
deps += nsl_amba.stream_fifo
deps += nsl_amba.stream_crc
deps += nsl_amba.stream_to_udp
