top = work.ip_top

ip-taxonomy = /AXI
ip-library = transactor
ip-name = axi4lite_jtag_transactor
ip-version = 1.0
ip-revision = 1
ip-display-name = AXI4-Lite JTAG ATE
ip-description = JTAG master transactor

include ../packaging.mk
