vhdl-sources += mii.pkg.vhd
vhdl-sources += mii_driver_resync.vhd
vhdl-sources += mii_driver_oversampled.vhd
vhdl-sources += mii_driver.vhd
vhdl-sources += mii_axi_driver_resync.vhd

deps += nsl_data.bytestream
deps += nsl_clocking.distribution
deps += nsl_clocking.interdomain
deps += nsl_bnoc.committed
deps += nsl_mii.flit
