target = extract
top = srclib.top
srclib-srcdir = $(SRC_DIR)/src
#target_part = xc6slx9
#target_package = tqg144
#target_speed = -2
#hwdep = xilinx
tool = extract


all: extract

include ../../build/build.mk
