vhdl-sources += audio_stream.pkg.vhd
vhdl-sources += hdmi_audio_stream_source.vhd

deps += nsl_amba.axi4_stream
deps += nsl_audio.pcm
deps += nsl_audio.pcm_stream
deps += nsl_hdmi.audio
deps += nsl_synthesis.assertion
