vhdl-sources += gaussian.pkg.vhd
vhdl-sources += gaussian_box_ufixed.vhd
vhdl-sources += gaussian_rc_ufixed.vhd
vhdl-sources += gaussian_ufixed.vhd

deps += nsl_dsp.rc
deps += nsl_dsp.box
deps += nsl_math.fixed
deps += nsl_math.arith
