vhdl-sources += jtag.pkg.vhd
vhdl-sources += jtag_ate.vhd
vhdl-sources += jtag_framed_ate.vhd
vhdl-sources += jtag_tap.vhd
vhdl-sources += jtag_tap_controller.vhd
vhdl-sources += jtag_tap_dr.vhd
deps += nsl.framed
