top = work.axis_ws2812

ip-taxonomy = /AXIS_Infrastructure
ip-library = nsl
ip-name = axis_ws2812
ip-display-name = AXI-Stream to WS2812 strip controller
ip-description = AXI-Stream to WS2812 strip controller
ip-version = 1.0
ip-revision = 1

include ../packaging.mk
