vhdl-sources += fpga_io.pkg.vhd
vhdl-sources += swd_main.vhd
constraint-sources += io.ucf

deps += nsl_coresight.dp
deps += nsl_coresight.ap
deps += nsl_coresight.dapbus
deps += nsl_indication.activity
deps += nsl_axi.ram
deps += nsl_hwdep.clock
deps += nsl_hwdep.reset

