vhdl-sources += tb.vhd

deps += nsl_bnoc.committed
deps += nsl_bnoc.testing
deps += nsl_data.text
deps += nsl_spi.slave
deps += nsl_simulation.driver
deps += nsl_bnoc.testing
deps += nsl_inet.ethernet
deps += nsl_line_coding.hdlc
