vhdl-sources += mii.vhd
vhdl-sources += mii_from_framed.vhd
vhdl-sources += mii_to_framed.vhd
vhdl-sources += rmii_from_framed.vhd
vhdl-sources += rmii_to_framed.vhd
vhdl-sources += rmii_noc.vhd
deps += nsl.fifo
deps += nsl.flit
