vhdl-sources += encoder.pkg.vhd
vhdl-sources += hdmi_13_encoder.vhd

deps += nsl_hdmi.hdmi
deps += nsl_data.crc
deps += nsl_data.endian
deps += nsl_data.bytestream
deps += nsl_line_coding.tmds
deps += nsl_color.ycbcr
deps += nsl_math.arith
deps += nsl_dvi.dvi
deps += nsl_dvi.encoder
